const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const W=48,H=48, gods=[{name:'Verdant',color:'#a5dd80'},{name:'Ember',color:'#e99168'}];
const tools=[['raise','Raise earth',9],['lower','Lower earth',9],['bloom','Bloom',20],['reveal','Revelation',32],['blight','Blight',30]];
const $=s=>document.querySelector(s),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let seed,rand,tiles,settlements,people,mana,tick,selected='raise',paused=false,logs=[],camera={x:0,y:0,zoom:1},drag=null,domination=0,won=false,river;
function rng(s){let x=s|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function hash(x,y,s){let n=(Math.imul(x|0,0x1f123bb5)^Math.imul(y|0,0x5f356495)^Math.imul(s|0,0x6c8e9cf5))|0;n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return ((n^(n>>>16))>>>0)/4294967296}
function noise(x,y,s){let ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);return (hash(ix,iy,s)*(1-fx)+hash(ix+1,iy,s)*fx)*(1-fy)+(hash(ix,iy+1,s)*(1-fx)+hash(ix+1,iy+1,s)*fx)*fy}
const at=(x,y)=>x>=0&&y>=0&&x<W&&y<H?tiles[y*W+x]:null;
function makeWorld(s){seed=s|0;rand=rng(seed);tick=0;mana=90;domination=0;won=false;logs=[];tiles=[];settlements=[];people=[];river=rand()*5;for(let y=0;y<H;y++)for(let x=0;x<W;x++){let nx=(x-W/2)/(W/2),ny=(y-H/2)/(H/2),edge=(nx*nx+ny*ny)*.62,n=noise(x/12,y/12,seed)*.6+noise(x/5,y/5,seed+8)*.3+noise(x/2,y/2,seed+41)*.1;let riverDist=Math.abs(y-(H/2+(noise(x/7,river,seed+23)-.5)*6));let h=clamp(Math.floor((n*.95-edge*.62+(riverDist<1.1?-.19:0))*8),0,5);tiles.push({h,fertility:clamp(noise(x/7,y/7,seed+99)*.85+.12,0,1),blight:0,tree:hash(x,y,seed+8)>.76,flower:hash(x,y,seed+11)>.88})}
 for(let i=0;i<8;i++){let side=i<4?0:1,x=Math.round((side?29:13)+(i%4-1.5)*4),y=Math.round(11+(i%4)*8);let spot=findLand(x,y);if(!spot)continue;let [sx,sy]=spot;for(let yy=sy-2;yy<=sy+2;yy++)for(let xx=sx-2;xx<=sx+2;xx++){let t=at(xx,yy);if(t&&Math.hypot(xx-sx,yy-sy)<2.3){t.h=2;t.fertility=Math.max(.55,t.fertility)}}let name=['Mossreach','Greenhollow','Willowford','Bracken','Ashfall','Cinderwatch','Redmere','Emberfall'][i];settlements.push({x:sx,y:sy,name,owner:side,pop:17+Math.floor(rand()*14),food:55,faith:[side===0?.9:.1,side===1?.9:.1],level:1,age:0});}
 for(let i=0;i<settlements.length;i++)for(let j=0;j<7;j++)spawnPerson(settlements[i],i);camera={x:0,y:0,zoom:1};log('A new world awakens. Shape the land and draw its people to you.');updateUI()}
function findLand(x,y){for(let r=0;r<7;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){let t=at(x+dx,y+dy);if(t&&t.h>=1&&t.h<=4)return[x+dx,y+dy]}return null}
function spawnPerson(s,home){people.push({x:s.x+(rand()-.5)*2,y:s.y+(rand()-.5)*2,tx:s.x,ty:s.y,home,god:s.owner,hunger:rand()*.4,fatigue:rand()*.4,fear:0,faith:.5+rand()*.4,bravery:rand(),devotion:rand(),social:rand(),action:'wander',age:0})}
function fuzzy(p,s){let danger=clamp(s.food<15?.35:0,0,1)+p.fear*.7,need=clamp(1-s.food/90,0,1),flat=clamp(localFlat(s.x,s.y),0,1);let scores={eat:p.hunger*.95+(s.food>5?.12:0),rest:p.fatigue*.9,farm:(1-p.fatigue)*need*.8+at(s.x,s.y).fertility*.32,build:(1-p.fatigue)*flat*.62+(s.food>30?.16:0),pray:p.devotion*.55+p.faith*.22,forage:need*.7+p.hunger*.3,flee:danger*(1-p.bravery)*1.1,wander:.18+p.social*.16};for(let k in scores)scores[k]+=(rand()-.5)*.14;return Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0]}
function localFlat(x,y){let h=at(x,y)?.h||0,n=0;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let t=at(x+dx,y+dy);if(t&&t.h===h&&h>0)n++}return n/25}
function simulate(){if(paused||won)return;tick++;mana=clamp(mana+settlements.reduce((n,s)=>n+(s.owner===0?s.pop*.0015:0),0),0,100);
 for(let i=0;i<tiles.length;i++)tiles[i].blight*=.994;
 for(const s of settlements){s.age++;let t=at(s.x,s.y),flat=localFlat(s.x,s.y),production=(.45+t.fertility*.7)*flat*(1-t.blight)*(s.pop/18),consumption=s.pop*.022;s.food=clamp(s.food+production-consumption,0,120);if(s.age%13===0){if(s.food>29&&flat>.34){s.pop=Math.min(170,s.pop+Math.max(1,Math.round(s.pop*.018)));s.food-=2}else if(s.food<3)s.pop=Math.max(3,s.pop-2)}s.level=clamp(Math.floor(s.pop/35)+1,1,4);
 let influence=[0,0];for(const other of settlements){let d=Math.hypot(s.x-other.x,s.y-other.y);if(d<17){let power=(other.pop/70+.2)/(1+d*.22);influence[other.owner]+=power}}for(let g=0;g<2;g++)influence[g]+=s.faith[g]*.72;let prosperity=clamp((s.food-25)/100,-.25,.4);influence[s.owner]+=prosperity;let target=influence[0]/Math.max(.01,influence[0]+influence[1]);s.faith[0]=clamp(s.faith[0]+(target-s.faith[0])*.007,0,1);s.faith[1]=1-s.faith[0];let next=s.faith[0]>.6?0:s.faith[1]>.6?1:s.owner;if(next!==s.owner){s.owner=next;log(`${s.name} now worships the ${gods[next].name}.`)} }
 for(const p of people){let s=settlements[p.home];if(!s)continue;p.age++;p.hunger=clamp(p.hunger+.014,0,1);p.fatigue=clamp(p.fatigue+.01,0,1);p.fear*=.94;if(p.age%6===0){p.action=fuzzy(p,s);let radius=p.action==='forage'?5:p.action==='wander'?3:1.7;p.tx=clamp(s.x+(rand()-.5)*radius*2,1,W-2);p.ty=clamp(s.y+(rand()-.5)*radius*2,1,H-2);if(p.action==='eat'&&s.food>1){p.hunger=clamp(p.hunger-.5,0,1);s.food-=.35}if(p.action==='rest')p.fatigue=clamp(p.fatigue-.52,0,1);if(p.action==='farm')s.food=clamp(s.food+.16,0,120);if(p.action==='pray')s.faith[p.god]=clamp(s.faith[p.god]+.001,0,1);let allegiance=s.faith[1-p.god];let resistance=.25+p.devotion*.48+p.faith*.18;let pressure=allegiance-resistance+(p.social-.5)*.13;if(pressure>.08&&rand()<pressure*.045){p.god=1-p.god;p.faith=.48}}let dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy);if(d>.1){p.x+=dx/d*.18;p.y+=dy/d*.18}}
 if(tick%38===0){for(let i=0;i<settlements.length;i++){let s=settlements[i],count=people.filter(p=>p.home===i).length;if(count<Math.min(14,Math.ceil(s.pop/9)))spawnPerson(s,i)}}
 if(tick%19===0)rivalAct();let own=settlements.reduce((n,s)=>n+s.pop*s.faith[0],0),all=settlements.reduce((n,s)=>n+s.pop,0);domination=own/all>=.7?domination+1:0;if(domination>=30){won=true;log('Victory! The Verdant commands the worship of the world.')}updateUI()}
function rivalAct(){let choices=settlements.filter(s=>s.owner===1),s=choices[Math.floor(rand()*choices.length)];if(!s)return;let t=at(s.x,s.y);if(rand()<.55){t.fertility=clamp(t.fertility+.12,0,1);s.food=clamp(s.food+7,0,120);log(`The Ember blesses ${s.name}.`)}else{let target=settlements.filter(v=>v.owner===0).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];if(target){target.faith[1]=clamp(target.faith[1]+.055,0,1);target.faith[0]=1-target.faith[1];log(`Ember signs appear near ${target.name}.`)}}}
function log(message){logs.unshift(message);logs=logs.slice(0,7);$('#log').innerHTML=logs.map(x=>`<p>${x}</p>`).join('')}
function updateUI(){let total=settlements.reduce((n,s)=>n+s.pop,0),own=settlements.reduce((n,s)=>n+s.pop*s.faith[0],0),pct=Math.round(own/total*100);$('#topstats').innerHTML=`<span>WORLD <b>${seed}</b></span><span>POPULATION <b>${total}</b></span><span>DAY <b>${Math.floor(tick/10)+1}</b></span>`;$('#mana').innerHTML=`FAITH ${Math.floor(mana)} / 100 <div class="meter"><i style="width:${mana}%"></i></div>`;$('#score').innerHTML=`<div class="row green">Verdant <b>${pct}%</b></div><div class="meter"><i style="width:${pct}%"></i></div><div class="row red">Ember <b>${100-pct}%</b></div><p>Hold 70% for 30 days to win. ${domination?`Current hold: ${domination}/30`:''}</p>`;$('#settlements').innerHTML=settlements.map(s=>`<div class="row"><b class="${s.owner?'red':'green'}">${s.name}</b><span>${s.pop} people · ${Math.floor(s.food)} food · ${Math.round(s.faith[0]*100)}% Verdant</span></div>`).join('');$('#worldinfo').innerHTML=`Seed: ${seed}<br>Day: ${Math.floor(tick/10)+1}<br>Settlements: ${settlements.length}<br>Visible followers: ${people.length}`;$('#status').textContent=won?'VICTORY · THE WORLD WORSHIPS YOU':paused?'PAUSED':`${tools.find(x=>x[0]===selected)[1].toUpperCase()} · ${tools.find(x=>x[0]===selected)[2]} FAITH`}
function act(x,y){let t=at(x,y),cost=tools.find(v=>v[0]===selected)[2];if(!t||mana<cost){if(mana<cost)log('Not enough faith for that action.');return}let close=settlements.filter(s=>Math.hypot(s.x-x,s.y-y)<4);if(selected==='raise'||selected==='lower'){if(close.some(s=>s.x===x&&s.y===y)){log('A settlement anchors this ground.');return}if(selected==='raise'&&t.h>=5||selected==='lower'&&t.h<=0)return;t.h+=selected==='raise'?1:-1;t.tree=false}else if(selected==='bloom'){for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let a=at(x+dx,y+dy);if(a&&Math.hypot(dx,dy)<=2.4){a.fertility=clamp(a.fertility+.27,0,1);a.blight*=.4}}for(let s of close)s.food=clamp(s.food+8,0,120)}else if(selected==='reveal'){for(let s of settlements)if(Math.hypot(s.x-x,s.y-y)<7){s.faith[0]=clamp(s.faith[0]+.1,0,1);s.faith[1]=1-s.faith[0]}for(let p of people)if(Math.hypot(p.x-x,p.y-y)<7)p.faith=clamp(p.faith+.12,0,1)}else if(selected==='blight'){for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let a=at(x+dx,y+dy);if(a&&Math.hypot(dx,dy)<=2.4)a.blight=clamp(a.blight+.48,0,1)}for(let s of close)s.food=Math.max(0,s.food-13)}mana-=cost;updateUI()}
function size(){let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0)}new ResizeObserver(size).observe(canvas);
const TW=28,TH=14,LIFT=6;function origin(){return{x:canvas.clientWidth/2+camera.x,y:canvas.clientHeight*.16+camera.y}}
function project(x,y,h=0){let o=origin();return{x:o.x+(x-y)*TW*camera.zoom,y:o.y+(x+y)*TH*camera.zoom-h*LIFT*camera.zoom}}
function polygon(points,fill,stroke){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.6*camera.zoom;ctx.stroke()}}
function render(){let w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#183c50';ctx.fillRect(0,0,w,h);let time=performance.now()*.001;for(let sum=0;sum<W+H-1;sum++)for(let y=Math.max(0,sum-W+1);y<=Math.min(H-1,sum);y++){let x=sum-y,t=at(x,y),p=project(x,y,t.h),z=camera.zoom;if(p.x<-70||p.x>w+70||p.y<-90||p.y>h+90)continue;let top={x:p.x,y:p.y-TH*z},right={x:p.x+TW*z,y:p.y},bottom={x:p.x,y:p.y+TH*z},left={x:p.x-TW*z,y:p.y};if(t.h>0){let color=t.h>=5?'#81847b':t.h===4?'#859677':t.h===3?'#668d64':t.h===2?'#6e9c69':'#adb17d';if(t.blight>.25)color='#827662';else if(t.fertility>.8&&t.h<=3)color='#78ab6a';let depth=Math.max(3,t.h*1.5)*z;polygon([left,bottom,{x:bottom.x,y:bottom.y+depth},{x:left.x,y:left.y+depth}],'#405948');polygon([bottom,right,{x:right.x,y:right.y+depth},{x:bottom.x,y:bottom.y+depth}],'#314b3e');polygon([top,right,bottom,left],color,'#3b634b55');if(t.tree&&t.h<4&&t.blight<.4){ctx.fillStyle='#36483a';ctx.fillRect(p.x-z,p.y-7*z,2*z,7*z);ctx.fillStyle=t.fertility>.6?'#284f3b':'#3b5944';ctx.beginPath();ctx.arc(p.x,p.y-9*z,(2+hash(x,y,seed)*2)*z,0,7);ctx.fill()}else if(t.flower&&t.h<4){ctx.fillStyle='#d7d9a5';ctx.fillRect(p.x,p.y-2*z,1.5*z,1.5*z)}}else{polygon([top,right,bottom,left],`rgba(46,105,127,${.36+Math.sin(time+x+y)*.05})`,'#31708a44')}}
 for(let s of settlements){let p=project(s.x,s.y,at(s.x,s.y).h),z=camera.zoom,c=gods[s.owner].color;ctx.fillStyle='#172924';ctx.beginPath();ctx.ellipse(p.x,p.y+5*z,12*z,5*z,0,0,7);ctx.fill();for(let i=0;i<s.level+1;i++){let bx=p.x+(i-(s.level)/2)*5*z,by=p.y-(i%2)*3*z;ctx.fillStyle='#d2b997';ctx.fillRect(bx-3*z,by-10*z,6*z,9*z);polygon([{x:bx-4*z,y:by-10*z},{x:bx,y:by-15*z},{x:bx+4*z,y:by-10*z}],c)}ctx.fillStyle=c;ctx.fillRect(p.x-1*z,p.y-25*z,2*z,12*z);polygon([{x:p.x+z,y:p.y-25*z},{x:p.x+9*z,y:p.y-22*z},{x:p.x+z,y:p.y-19*z}],c);if(z>.65){ctx.font=`${Math.max(9,11*z)}px DM Sans`;ctx.textAlign='center';ctx.fillStyle='#071c18';ctx.fillText(s.name,p.x+1,p.y-29*z+1);ctx.fillStyle='#fff3d9';ctx.fillText(s.name,p.x,p.y-29*z)}}
 for(let p of people){let t=at(Math.round(p.x),Math.round(p.y));if(!t||!t.h)continue;let pos=project(p.x,p.y,t.h),z=camera.zoom;ctx.fillStyle='#172320';ctx.beginPath();ctx.ellipse(pos.x,pos.y,2.5*z,1.2*z,0,0,7);ctx.fill();ctx.fillStyle=gods[p.god].color;ctx.fillRect(pos.x-1.4*z,pos.y-5*z,2.8*z,4*z);ctx.fillStyle='#dfc9a5';ctx.beginPath();ctx.arc(pos.x,pos.y-6*z,1.6*z,0,7);ctx.fill()}requestAnimationFrame(render)}requestAnimationFrame(render);
function tileFromScreen(px,py){let o=origin(),sx=(px-o.x)/camera.zoom,sy=(py-o.y)/camera.zoom;let xx=(sy/TH+sx/TW)/2,yy=(sy/TH-sx/TW)/2;let best=null,dist=1e9;for(let y=Math.max(0,Math.floor(yy)-5);y<=Math.min(H-1,Math.ceil(yy)+5);y++)for(let x=Math.max(0,Math.floor(xx)-5);x<=Math.min(W-1,Math.ceil(xx)+5);x++){let p=project(x,y,at(x,y).h),d=Math.abs(px-p.x)/TW+Math.abs(py-p.y)/TH;if(d<dist){dist=d;best=[x,y]}}return dist<camera.zoom*1.8?best:null}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,moved:false,button:e.button}});canvas.addEventListener('pointermove',e=>{if(drag){let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;if(drag.moved){camera.x+=dx;camera.y+=dy}drag.x=e.clientX;drag.y=e.clientY}});canvas.addEventListener('pointerup',e=>{if(!drag)return;let moved=drag.moved,button=drag.button;drag=null;if(moved)return;let r=canvas.getBoundingClientRect(),tile=tileFromScreen(e.clientX-r.left,e.clientY-r.top);if(!tile)return;let [x,y]=tile,s=settlements.find(v=>Math.hypot(v.x-x,v.y-y)<2);if(button===2){let t=at(x,y);$('#inspect').style.display='block';$('#inspect').textContent=s?`${s.name} · ${s.pop} people · ${Math.round(s.faith[0]*100)}% Verdant faith`:`Tile ${x}, ${y} · elevation ${t.h} · fertility ${Math.round(t.fertility*100)}%`;return}act(x,y)});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=clamp(camera.zoom*(e.deltaY>0?.9:1.1),.45,2.4)},{passive:false});
$('#tools').innerHTML=tools.map(([id,label,cost])=>`<button class="tool" data-tool="${id}">${label}<small>${cost} ✦</small></button>`).join('');$('#tools').addEventListener('click',e=>{let b=e.target.closest('[data-tool]');if(b){selected=b.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===b));updateUI()}});document.querySelector('[data-tool=raise]').classList.add('active');$('#newWorld').onclick=()=>makeWorld(Math.floor(Math.random()*999999));$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'RESUME':'PAUSE';updateUI()};$('#plus').onclick=()=>camera.zoom=clamp(camera.zoom*1.2,.45,2.4);$('#minus').onclick=()=>camera.zoom=clamp(camera.zoom/1.2,.45,2.4);$('#help').onclick=()=>$('#guide').showModal();$('#closeGuide').onclick=()=>$('#guide').close();makeWorld(new URLSearchParams(location.search).has('seed')?Number(new URLSearchParams(location.search).get('seed'))||12345:Math.floor(Math.random()*999999));setInterval(simulate,900);
