import * as THREE from '../vendor/three.module.js';
const $=s=>document.querySelector(s), W=42,H=30, clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const colors=[0x78c5ac,0xe48369,0xb9b7a5];
const stage=$('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color(0x567e8b);scene.fog=new THREE.Fog(0x567e8b,28,58);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;stage.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-13,13,9,-9,.1,100),target=new THREE.Vector3(0,0,0);let angle=Math.PI/4,zoom=1,drag=null;
scene.add(new THREE.HemisphereLight(0xd5eeff,0x4c5143,2.6));const sun=new THREE.DirectionalLight(0xffe5b0,2.9);sun.position.set(-13,23,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.bias=-.0005;scene.add(sun);
const water=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x376d78,roughness:.42,metalness:.14}));water.rotation.x=-Math.PI/2;water.position.y=.03;scene.add(water);
const terrain=new THREE.Group(),objects=new THREE.Group(),unitsGroup=new THREE.Group(),fxGroup=new THREE.Group();scene.add(terrain,objects,unitsGroup,fxGroup);
const box=new THREE.BoxGeometry(1,1,1),sphere=new THREE.SphereGeometry(1,10,8),cone=new THREE.ConeGeometry(1,1,8),cyl=new THREE.CylinderGeometry(1,1,1,8),ringGeo=new THREE.TorusGeometry(1,.035,5,28);
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.92,...extra});const landMats=[null,mat(0x988665),mat(0x869a66),mat(0x73a26a),mat(0x7e9569),mat(0x999a81)],sideMats=[null,mat(0x605747),mat(0x5e6650),mat(0x52684b),mat(0x53624d),mat(0x666b5c)];const woodMat=mat(0x725746),roofMats=[mat(0x446a56),mat(0xa45043)],stoneMat=mat(0xc0ad83),wildMat=mat(0xc8c0a4),trunkMat=mat(0x654c38),leafMats=[mat(0x294e3c),mat(0x38664a),mat(0x54825a)],waterMat=mat(0x9cc4bc,{transparent:true,opacity:.35}),terraceGold=mat(0xd1bd7b),terraceRough=mat(0xb17b68);
const DEVOTION_GOAL=500;let enemyPilgrimAt=15,seed=2026,tiles=[],buildings=[],people=[],faith=[45,45],devotion=[0,0],shrines=[{x:13,z:15,owner:2,progress:0,lock:0},{x:21,z:15,owner:2,progress:0,lock:0},{x:29,z:15,owner:2,progress:0,lock:0}],mode='inspect',running=true,speed=1,elapsed=0,tick=0,aiClock=0,ended='',logs=[],guideStep=0,toastTimer=0,fx=[],shaman,selectedSite=null;
const rand=(x,y,s=seed)=>{let n=Math.imul(x+11,374761393)+Math.imul(y+23,668265263)+Math.imul(s,2246822519);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967296};
const at=(x,z)=>x>=0&&z>=0&&x<W&&z<H?tiles[z*W+x]:null;const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);const height=(x,z)=>at(Math.round(x),Math.round(z))?.h||0;const pos=(x,z)=>new THREE.Vector3(x-W/2+.5,height(x,z)*.48,z-H/2+.5);
function mesh(geo,material,parent,x,y,z,sx=1,sy=1,sz=1){let o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function clear(group){while(group.children.length){let child=group.children[0];group.remove(child);if(child.geometry&&!([box,sphere,cone,cyl,ringGeo].includes(child.geometry)))child.geometry.dispose()}}
function log(s){logs.unshift(s);logs=logs.slice(0,5);$('#events').innerHTML=logs.map(v=>`<p>${v}</p>`).join('');toast(s)}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2600)}
function makeWorld(){clear(unitsGroup);clear(fxGroup);fx=[];seed=Math.floor(Math.random()*900000)+1000;tiles=[];buildings=[];people=[];faith=[45,45];devotion=[0,0];enemyPilgrimAt=15;shrines=[{x:13,z:15,owner:2,progress:0,lock:0},{x:21,z:15,owner:2,progress:0,lock:0},{x:29,z:15,owner:2,progress:0,lock:0}];elapsed=0;tick=0;aiClock=0;ended='';running=true;speed=1;guideStep=0;logs=[];mode='inspect';selectedSite=null;$('#sitePanel').hidden=true;$('#result').hidden=true;$('#pause').textContent='PAUSE';$('#speed').textContent='1× SPEED';for(let z=0;z<H;z++)for(let x=0;x<W;x++){let island=Math.min(x,W-1-x,z,H-1-z),noise=rand(Math.floor(x/3),Math.floor(z/3))*.7+rand(x,z)*.3;let h=island<2||noise<.18?0:clamp(Math.floor(noise*4.5),1,4);tiles.push({h,tree:h>0&&rand(x,z,seed+1)>.76,wood:0,building:null})}for(let camp of [{x:7,z:15},{x:34,z:15}])for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){let t=at(camp.x+dx,camp.z+dz);if(t){t.h=2;if(Math.abs(dx)<2&&Math.abs(dz)<2)t.tree=false}}for(let z=14;z<=16;z++)for(let x=10;x<=32;x++){let t=at(x,z);if(t)t.h=2}for(let shrine of shrines)for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;let x=shrine.x+dx,z=shrine.z+dz,t=at(x,z);if(t){t.h=(dx+dz+shrine.x)%3===0?2:(dx*dz>0?3:1);t.tree=false}}addBuilding(7,15,0,'hearth',true);addBuilding(34,15,1,'hearth',true);addBuilding(5,14,0,'hut',true);addBuilding(36,16,1,'hut',true);for(let [x,z] of [[10,12],[11,17],[30,12],[31,18]]){let t=at(x,z);t.h=2;t.tree=true}for(let [x,z,owner] of [[9,15,0],[32,15,1]]){at(x,z).tree=false;addBuilding(x,z,owner,'hut')}for(let i=0;i<5;i++){addPerson(0,6+rand(i,0),14+rand(i,1),'brave');addPerson(1,35+rand(i,2),15+rand(i,3),'brave')}for(let i=0;i<11;i++){let x=13+rand(i,5)*16,z=12+rand(i,6)*6;if(!validLand(Math.round(x),Math.round(z)))z=15;addPerson(2,x,z,'wild')};shaman=addPerson(0,7,16,'shaman');addPerson(1,34,14,'shaman');renderTerrain();renderObjects();updateUI();updateGuide();log('Grow your tribe and guide the shaman to the three sacred stones. First to 500 devotion wins.');cameraTarget(stage.clientWidth<760?10:21,15)}
function addBuilding(x,z,owner,type,complete=false){let t=at(x,z);if(!t||t.h<1||t.building)return null;let b={x,z,owner,type,progress:complete?1:0,wood:complete?3:0,blessed:false,pop:0,spawn:0};buildings.push(b);t.building=b;return b}
function addPerson(owner,x,z,type){let p={owner,x,z,type,goal:null,work:0,carry:0,idle:0,role:'worker',worshipSite:null,workSite:null,tendSite:null,tendCooldown:0,route:null,routeGoal:null,job:type==='wild'?'ROAMING':'IDLE'};people.push(p);return p}
function renderTerrain(){clear(terrain);for(let z=0;z<H;z++)for(let x=0;x<W;x++){let t=at(x,z);if(!t.h)continue;let p=pos(x,z),y=t.h*.48,material=landMats[t.h];mesh(box,sideMats[t.h],terrain,p.x,y/2-.015,p.z,.98,y,.98);mesh(box,material,terrain,p.x,y-.035,p.z,.99,.09,.99);if(rand(x,z,seed+71)>.65){let pebble=mesh(sphere,rand(x,z,seed+74)>.5?stoneMat:landMats[Math.min(5,t.h+1)],terrain,p.x+(rand(x,z,seed+75)-.5)*.6,y+.012,p.z+(rand(x,z,seed+76)-.5)*.6,.05,.03,.08);pebble.castShadow=false}let sacred=shrines.find(site=>Math.max(Math.abs(site.x-x),Math.abs(site.z-z))===1);if(sacred){let marker=mesh(ringGeo,t.h===height(sacred.x,sacred.z)?terraceGold:terraceRough,terrain,p.x,y+.04,p.z,.31,.31,.31);marker.rotation.x=Math.PI/2;marker.castShadow=false}}}
function renderObjects(){clear(objects);for(let z=0;z<H;z++)for(let x=0;x<W;x++){let t=at(x,z);if(!t.tree||!t.h)continue;let p=pos(x,z),v=rand(x,z,seed+2);mesh(cyl,trunkMat,objects,p.x,p.y+.24,p.z,.09,.5,.09);mesh(cone,leafMats[Math.floor(v*3)],objects,p.x,p.y+.66,p.z,.37,.8,.37);mesh(cone,leafMats[Math.floor(v*3)],objects,p.x,p.y+.93,p.z,.26,.62,.26)}for(let shrine of shrines){let p=pos(shrine.x,shrine.z),c=shrine.owner===2?stoneMat:gem[shrine.owner];mesh(cyl,stoneMat,objects,p.x,p.y+.12,p.z,.72,.24,.72);for(let i=0;i<5;i++){let a=i*Math.PI*2/5;mesh(box,stoneMat,objects,p.x+Math.sin(a)*.39,p.y+.32,p.z+Math.cos(a)*.39,.14,.38,.14)}mesh(cone,c,objects,p.x,p.y+.69,p.z,.22,.65,.22);if(shrine.lock>0){let halo=mesh(ringGeo,c,objects,p.x,p.y+.1,p.z,.62,.62,.62);halo.rotation.x=Math.PI/2}}for(let b of buildings){let p=pos(b.x,b.z),roof=roofMats[b.owner];if(b.progress<1){let marker=mesh(box,roof,objects,p.x,p.y+.025,p.z,.76,.05,.76);marker.material=roof;for(let dx of [-.31,.31])for(let dz of [-.31,.31])mesh(cyl,woodMat,objects,p.x+dx,p.y+.17,p.z+dz,.045,.32,.045);if(b.wood)mesh(box,woodMat,objects,p.x,p.y+.1,p.z,.4,.13,.4);continue}if(b.type==='hearth'){mesh(cyl,stoneMat,objects,p.x,p.y+.16,p.z,.78,.32,.78);mesh(cyl,roof,objects,p.x,p.y+.48,p.z,.45,.45,.45);mesh(cone,roof,objects,p.x,p.y+.92,p.z,.6,.55,.6);mesh(sphere,mat(b.owner===0?0xafffeb:0xffa28b,{emissive:b.owner===0?0x2f9d81:0x9d2d23,emissiveIntensity:1.5}),objects,p.x,p.y+1.2,p.z,.14,.14,.14)}else{let scale=1;mesh(box,woodMat,objects,p.x,p.y+.3,p.z,.78*scale,.58*scale,.7*scale);let r=mesh(cone,roof,objects,p.x,p.y+.7*scale,p.z,.64*scale,.4*scale,.64*scale);r.rotation.y=Math.PI/4;mesh(box,stoneMat,objects,p.x,p.y+.13,p.z+.37*scale,.16*scale,.24*scale,.02);if(b.blessed)mesh(sphere,gem[b.owner],objects,p.x,p.y+1.05,p.z,.12,.12,.12)}}}
// Each follower owns a small character rig. Geometry and materials are shared across rigs.
const skin=[mat(0xc89f79),mat(0xa97756),mat(0xb3a080)],cloth=[mat(0x397b76),mat(0xa04f43),mat(0x776c59)],trim=[mat(0x95d5ba),mat(0xebaa7c),mat(0xd7c29b)],hair=[mat(0x392d2b),mat(0x4b3026),mat(0x555047)],eyes=mat(0x252523),staffMat=mat(0x665038),gem=[mat(0x8fffe1,{emissive:0x39bbaa,emissiveIntensity:2}),mat(0xffac83,{emissive:0xd94c32,emissiveIntensity:2})],shadowMat=mat(0x12252a,{transparent:true,opacity:.3,depthWrite:false});
function followerRig(p){let owner=p.owner,kind=p.type,sh=kind==='shaman',wild=owner===2,group=new THREE.Group(),body=new THREE.Group();group.add(body);group.userData={body,legs:[],arms:[],kind:owner+':'+kind};unitsGroup.add(group);
 let base=owner===2?2:owner,scale=sh?1.28:1;body.scale.setScalar(scale);
 let shadow=mesh(sphere,shadowMat,group,0,.035,0,.27,.015,.22);shadow.castShadow=false;
 if(sh){let halo=mesh(ringGeo,gem[owner],group,0,.065,0,.42,.42,.42);halo.rotation.x=Math.PI/2;halo.castShadow=false;group.userData.halo=halo}
 for(let side of [-1,1]){let leg=new THREE.Group();leg.position.set(side*.105,.35,0);body.add(leg);mesh(cyl,wild?skin[2]:cloth[base],leg,0,-.15,0,.068,.31,.068);mesh(box,wild?skin[2]:staffMat,leg,0,-.3,.06,.1,.08,.19);group.userData.legs.push(leg)}
 if(sh){mesh(cone,cloth[base],body,0,.44,0,.31,.66,.28);mesh(cone,trim[base],body,0,.31,0,.28,.15,.27);mesh(sphere,cloth[base],body,0,.75,-.06,.26,.19,.21);mesh(sphere,trim[base],body,0,.82,.1,.18,.065,.12)}
 else{mesh(box,wild?skin[2]:cloth[base],body,0,.59,0,.38,.42,.23);mesh(box,wild?cloth[2]:trim[base],body,0,.39,.01,.39,.09,.26);if(!wild){mesh(box,staffMat,body,0,.67,-.15,.3,.28,.1);mesh(box,trim[base],body,0,.66,-.21,.31,.08,.055)}}
 for(let side of [-1,1]){let arm=new THREE.Group();arm.position.set(side*.245,sh?.79:.73,0);body.add(arm);mesh(cyl,sh?cloth[base]:skin[base],arm,side*.04,-.13,0,.07,.28,.07);mesh(sphere,skin[base],arm,side*.04,-.29,.01,.065,.065,.065);group.userData.arms.push(arm)}
 mesh(sphere,skin[base],body,0,sh?1.05:.96,.02,.17,.19,.15);mesh(sphere,hair[base],body,0,sh?1.18:1.075,-.045,.175,.09,.15);
 for(let side of [-1,1])mesh(sphere,eyes,body,side*.072,sh?1.065:.975,.16,.018,.021,.011);
 if(sh){let hood=mesh(cone,cloth[base],body,0,1.23,-.065,.225,.35,.23);hood.rotation.x=-.15;mesh(cyl,staffMat,body,.35,.7,.08,.028,1.1,.028);mesh(sphere,gem[owner],body,.35,1.28,.08,.115,.12,.115);mesh(ringGeo,gem[owner],body,.35,1.28,.08,.18,.18,.18);}
 else if(wild){mesh(cone,hair[2],body,0,1.11,-.04,.2,.23,.2);mesh(sphere,hair[2],body,0,.87,-.025,.16,.06,.16)}
 else{let cap=mesh(cone,cloth[base],body,0,1.12,-.02,.19,.15,.18);cap.rotation.z=-.17;mesh(box,trim[base],body,0,1.055,.02,.35,.045,.32);}
 if(!sh&&!wild){let bundle=mesh(cyl,woodMat,body,0,.55,.25,.065,.38,.065);bundle.rotation.z=Math.PI/2;bundle.visible=false;group.userData.bundle=bundle;let halo=mesh(ringGeo,gem[owner],group,0,.07,0,.29,.29,.29);halo.rotation.x=Math.PI/2;halo.visible=false;halo.castShadow=false;group.userData.worshipHalo=halo}return group}
function renderUnits(time){for(let child of [...unitsGroup.children])if(!people.some(p=>p.visual===child))unitsGroup.remove(child);
 for(let p of people){let kind=p.owner+':'+p.type;if(!p.visual||p.visual.userData.kind!==kind){if(p.visual)unitsGroup.remove(p.visual);p.visual=followerRig(p);p.lastX=p.x;p.lastZ=p.z;p.walkPhase=0}
 let rig=p.visual,v=pos(p.x,p.z),dx=p.x-p.lastX,dz=p.z-p.lastZ,moving=Math.hypot(dx,dz)>.0005;rig.position.set(v.x,v.y,v.z);if(moving){rig.rotation.y=Math.atan2(dx,dz);p.walkPhase+=Math.hypot(dx,dz)*18}p.lastX=p.x;p.lastZ=p.z;
 let swing=moving?Math.sin(p.walkPhase)*.5:Math.sin(time*.0015+p.x)*.035;rig.userData.legs[0].rotation.x=swing;rig.userData.legs[1].rotation.x=-swing;rig.userData.arms[0].rotation.x=-swing*.7;rig.userData.arms[1].rotation.x=swing*.7;rig.userData.body.position.y=(moving?Math.abs(Math.sin(p.walkPhase))*.025:Math.sin(time*.002+p.x)*.018);if(rig.userData.halo)rig.userData.halo.rotation.z=time*.00045;
 if(rig.userData.bundle)rig.userData.bundle.visible=!!p.carry;if(rig.userData.worshipHalo)rig.userData.worshipHalo.visible=p.role==='worshipper'||!!p.tendSite;}}

function validLand(x,z){let t=at(x,z);return !!t&&t.h>0}
function nearest(list,p){let best=null,d=Infinity;for(let item of list){let n=dist(item,p);if(n<d){best=item;d=n}}return best}
function landRoute(from,to){let sx=Math.round(from.x),sz=Math.round(from.z),gx=Math.round(to.x),gz=Math.round(to.z),start=sz*W+sx,end=gz*W+gx;if(!validLand(gx,gz))return null;let queue=[start],seen=new Int32Array(W*H).fill(-1);seen[start]=start;for(let head=0;head<queue.length;head++){let index=queue[head];if(index===end)break;let x=index%W,z=Math.floor(index/W);for(let [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,nz=z+dz,ni=nz*W+nx;if(validLand(nx,nz)&&seen[ni]===-1){seen[ni]=index;queue.push(ni)}}}if(seen[end]===-1)return null;let path=[];for(let i=end;i!==start;i=seen[i])path.push({x:i%W,z:Math.floor(i/W)});return path.reverse()}
function move(p,goal,dt,rate=1){if(!goal)return;if(p.routeGoal!==goal){p.route=null;p.routeGoal=goal}let destination=p.route?.length?p.route[0]:goal,dx=destination.x-p.x,dz=destination.z-p.z,d=Math.hypot(dx,dz);if(d<.14){if(p.route?.length){p.route.shift();return}p.goal=null;p.route=null;return}let step=Math.min(d,dt*rate),x=p.x+dx/d*step,z=p.z+dz/d*step;if(validLand(Math.round(x),Math.round(z))){p.x=x;p.z=z}else{p.route=landRoute(p,goal);if(!p.route)p.goal=null}}
function validWorshipSite(target,owner){return shrines.includes(target)?target.owner===owner:buildings.includes(target)&&target.owner===owner&&target.blessed&&target.progress===1}
function siteNeeds(site,owner){let huts=buildings.filter(b=>b.owner===owner&&b.type==='hut'&&b.progress===1&&dist(b,site)<5).length,workers=people.filter(p=>p.owner===owner&&p.type==='brave'&&p.role==='worker'&&dist(p,site)<5).length;return {huts,workers,healthy:huts>=1&&workers>=2}}
function siteBelief(site){return site.belief??35}
function terraceScore(site){let level=height(site.x,site.z),matched=0;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if((dx||dz)&&height(site.x+dx,site.z+dz)===level)matched++;return matched}
function terrainBrush(x,z,dir,apply=false){let t=at(x,z),terrace=shrines.find(site=>site.owner===0&&Math.max(Math.abs(site.x-x),Math.abs(site.z-z))===1)||null;if(!t||t.building||shrines.some(site=>site.x===x&&site.z===z))return {changed:0,terrace};if(terrace){let target=height(terrace.x,terrace.z);if(dir>0&&t.h>=target||dir<0&&t.h<=target)return {changed:0,terrace}}let next=clamp(t.h+dir,0,5);if(next===t.h)return {changed:0,terrace};if(apply){t.h=next;if(!next)t.tree=false}return {changed:1,terrace}}
function bestTerraceBrush(site){let best=null;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;let x=site.x+dx,z=site.z+dz;for(let dir of [-1,1]){let plan=terrainBrush(x,z,dir);if(!best||plan.changed>best.changed)best={x,z,dir,changed:plan.changed}}}return best?.changed?best:null}
function assignWorshippers(owner,target,count=2){let capacity=shrines.includes(target)?4:2,current=people.filter(p=>p.owner===owner&&p.worshipSite===target).length,workers=people.filter(p=>p.owner===owner&&p.type==='brave'&&p.role==='worker'&&!p.carry).sort((a,b)=>dist(a,target)-dist(b,target));let chosen=workers.slice(0,Math.max(0,Math.min(count,capacity-current,workers.length-3)));for(let p of chosen){p.role='worshipper';p.worshipSite=target;p.workSite=null;p.tendSite=null;p.goal={x:target.x+(p.x>target.x?.55:-.55),z:target.z};p.job='GOING TO WORSHIP'}return chosen.length}
function pickWorkSite(p){let sites=buildings.filter(b=>b.owner===p.owner&&b.progress<1);if(!sites.length)return null;if(p.workSite&&sites.includes(p.workSite))return p.workSite;let available=sites.filter(b=>people.filter(q=>q.owner===p.owner&&q.workSite===b&&q.role==='worker').length<3);if(!available.length)return p.carry?nearest(sites,p):null;return available.reduce((best,b)=>!best||dist(p,b)<dist(p,best)?b:best,null)}
function income(owner){let followers=people.filter(p=>p.owner===owner).length,sites=shrines.filter(s=>s.owner===owner).length,blessed=buildings.filter(b=>b.owner===owner&&b.blessed&&b.progress===1).length,worship=people.filter(p=>p.owner===owner&&p.role==='worshipper'&&validWorshipSite(p.worshipSite,owner)&&dist(p,p.worshipSite)<1.5).reduce((sum,p)=>sum+(shrines.includes(p.worshipSite)?.9:.65)*(.65+siteBelief(p.worshipSite)*.009),0),terraces=shrines.filter(s=>s.owner===owner).reduce((sum,s)=>sum+terraceScore(s)*.16,0);return .2+followers*.045+sites*.45+blessed*.3+worship+terraces}
function siteWorshippers(site){return people.filter(p=>p.owner===0&&p.role==='worshipper'&&p.worshipSite===site&&dist(p,site)<1.5).length}
function festivalReady(site){return validWorshipSite(site,0)&&siteBelief(site)>=55&&siteWorshippers(site)>=2&&(site.festivalUntil||0)<=elapsed}
function festival(site){if(!festivalReady(site))return toast('Festival needs 55 belief, two worshippers on site, and no cooldown.');if(faith[0]<35)return toast('Save 35 faith for a festival.');faith[0]-=35;let reward=Math.round(24+siteBelief(site)*.18+(shrines.includes(site)?terraceScore(site)*2:0));devotion[0]+=reward;site.belief=clamp(siteBelief(site)-15,10,100);site.festivalUntil=elapsed+40;ping(site.x,site.z,gem[0]);log(`Festival! +${reward} devotion. Belief falls briefly while the village celebrates.`);if(devotion[0]>=DEVOTION_GOAL)finish(true);updateUI()}
function canPlaceHut(x,z){let t=at(x,z),point={x,z};return !!t&&!!t.h&&!t.building&&!t.tree&&!shrines.some(s=>dist(s,point)<1.5)&&(dist(point,{x:7,z:15})<=11||buildings.some(b=>b.owner===0&&dist(point,b)<5)||shrines.some(s=>s.owner===0&&dist(point,s)<5))}
function hutLocation(site){let spots=[];for(let z=Math.max(1,site.z-4);z<=Math.min(H-2,site.z+4);z++)for(let x=Math.max(1,site.x-4);x<=Math.min(W-2,site.x+4);x++)if(canPlaceHut(x,z)&&dist({x,z},site)<4.5)spots.push({x,z});spots.sort((a,b)=>dist(a,site)-dist(b,site));return spots[0]||null}
function nextMove(){let owned=[...shrines,...buildings].filter(s=>validWorshipSite(s,0)),ready=owned.find(s=>festivalReady(s)&&faith[0]>=35);if(ready)return {title:'HOLD A FESTIVAL',body:`${shrines.includes(ready)?'Stone':'Blessed hut'} at ${ready.x}, ${ready.z} is ready. Spend 35 faith for an immediate devotion surge.`,label:'CELEBRATE',run:()=>festival(ready)};
 let empty=owned.find(s=>siteWorshippers(s)<2&&people.filter(p=>p.owner===0&&p.type==='brave'&&p.role==='worker'&&!p.carry).length>=4);if(empty)return {title:'GROW YOUR FAITH',body:'Assign two workers to worship here. You can recall them when you need builders.',label:'ASSIGN WORSHIPPERS',run:()=>{let n=assignWorshippers(0,empty,2);cameraTarget(empty.x,empty.z);if(n)log(`${n} followers head to worship. Their faith rises when they arrive.`);updateUI()}};
 let rough=shrines.find(s=>s.owner===0&&terraceScore(s)<8),brush=rough&&bestTerraceBrush(rough);if(brush){let range=dist(shaman,brush);return {title:'SCULPT A SACRED TERRACE',body:`Stone at ${rough.x}, ${rough.z}: ${terraceScore(rough)}/8 tiles level. One red tile can be aligned with ${brush.dir>0?'Raise':'Lower'} Land for 4 faith. Gold markers are level; red markers need work.`,label:range>5.5?'SEND SHAMAN':faith[0]<4?'SHOW TERRACE':'SHAPE TILE · 4',run:()=>{cameraTarget(rough.x,rough.z);if(range>5.5){shaman.goal={x:rough.x,z:rough.z};toast('Shaman heading to the sacred terrace.')}else if(faith[0]<4)toast('Need 4 faith to shape the terrace.');else{let result=terrainBrush(brush.x,brush.z,brush.dir,true);faith[0]-=4;renderTerrain();renderObjects();ping(brush.x,brush.z,gem[0]);log('One terrace tile aligned. Sacred stone faith income rises.')}updateUI()}}}
 let neglected=owned.find(s=>!siteNeeds(s,0).healthy);if(neglected){let needs=siteNeeds(neglected,0),planned=buildings.some(b=>b.owner===0&&b.type==='hut'&&b.progress<1&&dist(b,neglected)<5),spot=needs.huts===0&&!planned?hutLocation(neglected):null;if(spot)return {title:'SETTLE BY THE STONE',body:`Plan a hut at ${spot.x}, ${spot.z}. Workers will build it; a nearby village strengthens belief.`,label:'PLAN NEARBY HUT',run:()=>{addBuilding(spot.x,spot.z,0,'hut');renderObjects();cameraTarget(spot.x,spot.z);ping(spot.x,spot.z,gem[0]);log('A hut is planned beside your worship site. Workers will gather wood and build it.');guideAdvance(1);updateUI()}};return {title:planned?'HUT UNDER CONSTRUCTION':'STRENGTHEN BELIEF',body:planned?'Workers are gathering wood and building near this site. Claim another stone or welcome followers while they work.':`This site needs two working followers nearby. Recall worshippers or grow your village.`,label:'SHOW SITE',run:()=>{selectedSite=neglected;mode='inspect';cameraTarget(neglected.x,neglected.z);updateUI()}}}
 let target=nearest(shrines.filter(s=>s.owner!==0&&s.lock<=0),shaman);if(target)return {title:'REACH A SACRED STONE',body:`Send your shaman to the stone at ${target.x}, ${target.z}. Holding it for three seconds claims it without spending faith.`,label:'SEND SHAMAN',run:()=>{shaman.goal={x:target.x,z:target.z};cameraTarget(target.x,target.z);toast('Shaman is travelling to the sacred stone.');updateUI()}};
 return {title:'EXPAND YOUR VILLAGE',body:'Place a hut near a worship site to grow workers and belief. Completed huts can become new worship sites.',label:'PLACE A HUT',run:()=>{mode='hut';cameraTarget(shaman.x,shaman.z);updateUI()}}}
function updateDecision(){let choice=nextMove();$('#decisionTitle').textContent=choice.title;$('#decisionBody').textContent=choice.body;$('#decisionAction').textContent=choice.label;$('#decisionAction').onclick=choice.run}
function updateSitePanel(){let panel=$('#sitePanel'),site=selectedSite;if(!site||!validWorshipSite(site,0)){panel.hidden=true;selectedSite=null;return}let needs=siteNeeds(site,0),assigned=people.filter(p=>p.owner===0&&p.worshipSite===site).length,cooldown=Math.max(0,Math.ceil((site.festivalUntil||0)-elapsed));panel.hidden=false;let html=`<b>${shrines.includes(site)?'SACRED STONE':'BLESSED HUT'} · ${Math.round(siteBelief(site))}% BELIEF</b><p>${needs.healthy?'Belief rising':'Belief falling'} · ${needs.huts} completed hut${needs.huts===1?'':'s'} · ${needs.workers} nearby workers<br>${assigned} assigned worshippers · ${shrines.includes(site)?`Terrace ${terraceScore(site)}/8 · `:''}${cooldown?`Festival ready in ${cooldown}s`:'Festival needs 55 belief and 2 worshippers'}</p><div><button data-site-action="assign" ${assigned>= (shrines.includes(site)?4:2)?'disabled':''}>ASSIGN 2</button><button data-site-action="recall" ${!assigned?'disabled':''}>RECALL</button><button data-site-action="festival" ${!festivalReady(site)||faith[0]<35?'disabled':''}>FESTIVAL · 35</button><button data-site-action="close">CLOSE</button></div>`;if(panel.innerHTML!==html)panel.innerHTML=html}

function ai(dt){
 elapsed+=dt;aiClock+=dt;
 for(let site of [...shrines,...buildings.filter(b=>b.blessed&&b.progress===1)]){if(site.owner>1)continue;let needs=siteNeeds(site,site.owner),old=siteBelief(site);site.belief=clamp(old+(needs.healthy?.45+(shrines.includes(site)?terraceScore(site)*.06:0):-.7)*dt,10,100);if(site.owner===0&&old<70&&site.belief>=70)log('A thriving settlement strengthens belief at a nearby worship site.')}
 for(let owner=0;owner<2;owner++){let rate=income(owner),previous=devotion[owner];faith[owner]=clamp(faith[owner]+rate*dt,0,160);devotion[owner]+=rate*dt;if(owner===0&&Math.floor(previous/50)<Math.floor(devotion[owner]/50))log(`${Math.floor(devotion[owner])} devotion. Your faith is taking root.`)}
 for(let site of shrines){site.lock=Math.max(0,site.lock-dt);let visiting=people.filter(p=>p.type==='shaman'&&dist(p,site)<1.55),capturer=visiting.length===1?visiting[0].owner:2;if(capturer!==2&&capturer!==site.owner&&site.lock<=0){site.progress+=dt;if(site.progress>=3){site.owner=capturer;site.belief=35;site.progress=0;renderObjects();log(capturer===0?'Sacred stone claimed: faith flows to your tribe.':'Ember claimed a sacred stone.');if(capturer===0)guideAdvance(2);else{enemyPilgrimAt=elapsed+35;assignWorshippers(1,site,1)}}}else site.progress=Math.max(0,site.progress-dt*.5)}
 for(let p of [...people]){
  if(p.type==='wild'){p.job='ROAMING';p.idle-=dt;if(p.idle<=0&&!p.goal){let x=clamp(Math.round(p.x+(rand(Math.floor(elapsed),people.indexOf(p))-.5)*4),1,W-2),z=clamp(Math.round(p.z+(rand(people.indexOf(p),Math.floor(elapsed))-.5)*4),1,H-2);if(validLand(x,z))p.goal={x,z};p.idle=3+rand(x,z)*3}if(p.goal)move(p,p.goal,dt,.45);continue}
  let own=p.owner;if(p.role==='worshipper'){if(!validWorshipSite(p.worshipSite,own)){p.role='worker';p.worshipSite=null;p.goal=null;p.job='RETURNING TO WORK'}else{if(p.goal)move(p,p.goal,dt,1.15);p.job=p.goal?'GOING TO WORSHIP':'WORSHIPPING';continue}}
  if(p.type==='brave'&&p.role==='worker'&&p.job==='VISITING HOMES'&&buildings.some(b=>b.owner===own&&b.progress<1))p.goal=null;
  if(p.type==='brave'&&p.tendSite){if(p.tendSite.owner!==own||buildings.some(b=>b.owner===own&&b.progress<1)){p.tendSite=null;p.goal=null;p.work=0}else{p.job='TENDING SHRINE';if(dist(p,p.tendSite)>1.35){if(!p.goal)p.goal={x:p.tendSite.x+(p.x>p.tendSite.x?.8:-.8),z:p.tendSite.z};move(p,p.goal,dt,1.15)}else{p.goal=null;p.work+=dt;if(p.work>=3){p.tendSite.belief=clamp(siteBelief(p.tendSite)+4,10,100);p.tendSite=null;p.tendCooldown=elapsed+22;p.work=0}}continue}}
  if(p.goal){move(p,p.goal,dt,p.type==='shaman'?1.5:1.3);continue}
  if(p.type==='shaman'){if(own===1){let target=elapsed>=enemyPilgrimAt?nearest(shrines.filter(s=>s.owner!==1&&s.lock<=0),p):null;if(target){if(dist(p,target)>1.25)p.goal={x:target.x,z:target.z}}else{let wild=nearest(people.filter(q=>q.owner===2),p);if(wild&&faith[1]>=20&&dist(wild,p)<4){wild.owner=1;wild.type='brave';wild.goal=null;faith[1]-=20;log('Ember welcomed a wildman to its tribe.')}}}continue}
  let site=pickWorkSite(p);p.workSite=site;
  if(site){if(p.carry){p.job='HAULING WOOD';if(dist(p,site)>1){p.goal={x:site.x+(p.x>site.x?.7:-.7),z:site.z};continue}site.wood=Math.min(3,site.wood+1);p.carry=0;renderObjects();if(site.wood===3&&own===0)log('Wood delivered. Braves are building the hut.');continue}
   if(site.wood<3){p.job='GATHERING WOOD';let trees=[];for(let z=Math.max(1,site.z-9);z<=Math.min(H-2,site.z+9);z++)for(let x=Math.max(1,site.x-9);x<=Math.min(W-2,site.x+9);x++)if(at(x,z)?.tree&&dist({x,z},site)<=9)trees.push({x,z});let tree=nearest(trees,p);if(tree){if(dist(p,tree)>.6)p.goal=tree;else{p.work+=dt;if(p.work>.75){p.work=0;at(tree.x,tree.z).tree=false;p.carry=1;renderObjects()}}continue}}
   if(site.wood>=3){p.job='BUILDING HUT';if(dist(p,site)>1){p.goal={x:site.x+(p.x>site.x?.7:-.7),z:site.z};continue}site.progress=clamp(site.progress+dt*.16,0,1);if(site.progress===1){log(`${own?'Ember':'Your'} hut completed.`);renderObjects()}continue}}
  let care=nearest(shrines.filter(s=>s.owner===own&&siteBelief(s)<90&&!people.some(q=>q!==p&&q.tendSite===s)),p);if(care&&dist(p,care)<9&&elapsed>=p.tendCooldown){p.tendSite=care;p.goal=null;p.work=0;p.job='TENDING SHRINE';continue}
  p.job='VISITING HOMES';p.idle-=dt;if(p.idle<=0){let homes=buildings.filter(b=>b.owner===own&&b.progress===1),home=nearest(homes,p);if(home){let x=clamp(home.x+Math.round((rand(Math.floor(elapsed),people.indexOf(p)+7)-.5)*5),1,W-2),z=clamp(home.z+Math.round((rand(people.indexOf(p)+9,Math.floor(elapsed))-.5)*5),1,H-2);if(validLand(x,z))p.goal={x,z}}p.idle=3+rand(Math.floor(elapsed),people.indexOf(p))*3}
 }
 for(let b of buildings){if(b.progress<1)continue;let nearby=people.filter(p=>p.owner===b.owner&&p.type==='brave'&&p.role==='worker'&&dist(p,b)<3).length;b.pop=nearby;b.spawn+=dt*(b.type==='hut'?.105:.025)*(1+Math.min(nearby,3)*.23);if(b.spawn>=1&&people.filter(p=>p.owner===b.owner).length<35){b.spawn=0;addPerson(b.owner,b.x+.35,b.z+.35,'brave');if(b.owner===0)log('A new brave joins your village: faith income rises.')}}
 if(aiClock>26){aiClock=0;let camp=buildings.find(b=>b.owner===1&&b.type==='hearth');if(camp){let x=camp.x-2-Math.floor(rand(Math.floor(elapsed),1)*3),z=camp.z+(rand(Math.floor(elapsed),2)>.5?2:-2);if(validLand(x,z)&&!at(x,z).building){at(x,z).tree=false;addBuilding(x,z,1,'hut');renderObjects();log('Ember planned another hut.')}let hut=buildings.find(b=>b.owner===1&&b.type==='hut'&&b.progress===1&&!b.blessed);if(hut&&faith[1]>=30){hut.blessed=true;hut.belief=35;faith[1]-=30;assignWorshippers(1,hut,1);renderObjects();log('Ember blessed a hut and called worshippers.')}for(let site of shrines.filter(s=>s.owner===1))assignWorshippers(1,site,1)}}
 if(devotion[0]>=DEVOTION_GOAL||devotion[1]>=DEVOTION_GOAL)finish(devotion[0]>=DEVOTION_GOAL&&devotion[0]>=devotion[1]);updateUI()
}

function ping(x,z,material){let p=pos(x,z),marker=mesh(ringGeo,material,fxGroup,p.x,p.y+.08,p.z,.3,.3,.3);marker.rotation.x=Math.PI/2;marker.castShadow=false;fx.push({marker,born:performance.now()})}
function finish(win){if(ended)return;ended=win?'victory':'defeat';running=false;$('#result').hidden=false;$('#result').innerHTML=`<h2>${win?'YOUR FAITH FLOURISHES':'EMBER REACHES THE PEOPLE FIRST'}</h2><p>${Math.floor(devotion[0])} to ${Math.floor(devotion[1])} devotion. ${win?'Your people and sacred sites formed a flourishing faith.':'Try balancing new followers, blessed huts and the sacred stones.'}</p><button id="again">PLAY AGAIN</button>`;$('#again').onclick=makeWorld}
const commands=[['move','MOVE SHAMAN','Free'],['hut','PLACE HUT','Braves build'],['worship','WORSHIP','Assign 2'],['recall','RECALL','Return to work'],['inspect','INSPECT','Free']];const spells=[['convert','CONVERT','20 faith'],['bless','BLESS HUT','30 faith'],['ritual','RITUAL','30–45 faith'],['raise','RAISE LAND','4 faith'],['lower','LOWER LAND','4 faith'],['bridge','LAND BRIDGE','30 faith']];
function setupButtons(){for(let [el,items] of [['#commands',commands],['#spells',spells]])$(el).innerHTML=items.map(([id,label,cost])=>`<button data-mode="${id}">${label}<small>${cost}</small></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;updateUI()})}
const spellCosts={convert:20,bless:30,raise:4,lower:4,bridge:30};const hints={move:'Move your shaman near a sacred stone; hold it for three seconds to claim.',hut:'Build huts to grow followers. Workers gather wood.',worship:'Assign workers to a stone or blessed hut. Nearby completed huts and working braves strengthen local belief and increase their faith yield.',recall:'Click a sacred stone or blessed hut to return its worshippers to work.',inspect:'Click a follower, hut or sacred stone for details.',convert:'Spend 20 faith to welcome a wildman near the shaman.',bless:'Spend 30 faith to bless a completed friendly hut for permanent income.',ritual:'Claim a nearby stone for 45 faith, or protect your stone for 30 faith and 25 seconds.',raise:'Raise one clicked tile for 4 faith. Red terrace tiles rise toward the stone height.',lower:'Lower one clicked tile for 4 faith. Red terrace tiles fall toward the stone height.',bridge:'Cross a water gap for 30 faith.'};
function action(x,z){let t=at(x,z);if(!t||ended)return;let point={x,z},range=dist(shaman,point),site=nearest(shrines,point);
 if(mode==='inspect'){let sacred=shrines.find(s=>Math.max(Math.abs(s.x-x),Math.abs(s.z-z))===1);if(sacred&&sacred.owner===0){selectedSite=sacred;updateSitePanel();toast(`Terrace ${terraceScore(sacred)}/8 · tile height ${t.h}, stone height ${height(sacred.x,sacred.z)}. Shape the red marked tiles.`);return}let blessed=nearest(buildings.filter(b=>b.owner===0&&b.blessed&&b.progress===1),point),focus=site&&dist(site,point)<1?site:blessed&&dist(blessed,point)<.9?blessed:null;if(focus&&validWorshipSite(focus,0)){selectedSite=focus;updateSitePanel();toast('Use the site card for worship, recall or a festival.');return}if(site&&dist(site,point)<1)toast(`Sacred stone · ${site.owner===2?'unclaimed':site.owner===0?'yours':'Ember'} · ${people.filter(p=>p.worshipSite===site).length}/4 worshippers${site.owner<2?' · belief '+Math.round(siteBelief(site))+'% '+(siteNeeds(site,site.owner).healthy?'↑':'↓ need hut + 2 workers nearby'):''}${site.lock?' · protected '+Math.ceil(site.lock)+'s':''}`);else{let person=nearest(people,point),building=nearest(buildings,point);if(person&&dist(person,point)<.7)toast(`${person.owner===2?'Wildman':person.owner?'Ember':'Verdant'} ${person.type} · ${person.job||'IDLE'}`);else if(building&&dist(building,point)<.9)toast(`${building.owner?'Ember':'Your'} ${building.type} · ${building.blessed?'belief '+Math.round(siteBelief(building))+'% '+(siteNeeds(building,building.owner).healthy?'↑':'↓ need hut + 2 workers nearby')+' · ':''}${Math.round(building.progress*100)}% built`);else toast(`Land height ${t.h} · ${t.tree?'trees':'clear'}`)}return}
 if(mode==='worship'||mode==='recall'){let target=site&&dist(site,point)<1?site:nearest(buildings.filter(b=>b.owner===0&&b.blessed&&b.progress===1),point);if(!target||dist(target,point)>1)return toast('Click an owned sacred stone or a blessed hut.');if(mode==='worship'){if(!validWorshipSite(target,0))return toast('Claim the stone or bless the hut first.');let count=assignWorshippers(0,target,2);if(!count)return toast('Need at least three free workers, or this site is full.');ping(target.x,target.z,gem[0]);log(`${count} followers begin worship. Faith rises when they arrive; fewer workers remain.`);guideAdvance(3)}else{let count=0;for(let p of people.filter(p=>p.owner===0&&p.worshipSite===target)){p.role='worker';p.worshipSite=null;p.goal=null;p.job='RETURNING TO WORK';count++}if(!count)return toast('No worshippers assigned here.');log(`${count} followers return to building and gathering.`)}updateUI();return}
 if(mode==='move'){if(!t.h)return toast('Your shaman cannot cross water.');shaman.goal=point;ping(x,z,gem[0]);toast('Shaman moving toward the marker.');return}
 if(mode==='hut'){if(!canPlaceHut(x,z))return toast('Place a hut on clear land near your village, away from a sacred stone.');addBuilding(x,z,0,'hut');ping(x,z,gem[0]);renderObjects();log('Hut planned. Braves will gather wood and build it.');guideAdvance(1);return}
 if(mode==='ritual'){if(!site||dist(site,point)>1.1)return toast('Click a sacred stone.');if(dist(shaman,site)>3)return toast('Bring the shaman within three tiles of the stone.');let cost=site.owner===0?30:45;if(faith[0]<cost)return toast(`Need ${cost} faith for this ritual.`);faith[0]-=cost;site.owner=0;site.belief=35;site.progress=0;site.lock=25;renderObjects();ping(site.x,site.z,gem[0]);log(`Ritual completed. This sacred stone is protected for 25 seconds.`);guideAdvance(2);updateUI();return}
 let cost=spellCosts[mode];if(faith[0]<cost)return toast(`Need ${cost} faith. Followers and sacred stones generate it.`);if(range>5.5)return toast('Out of range. Move the shaman closer first.');
 if(mode==='convert'){let wild=nearest(people.filter(p=>p.owner===2),point);if(!wild||dist(wild,point)>.8)return toast('Target a grey wildman.');wild.owner=0;wild.type='brave';wild.goal=null;faith[0]-=cost;log('Wildman joined your tribe. More followers generate more faith.');guideAdvance(0)}
 else if(mode==='bless'){let hut=nearest(buildings.filter(b=>b.owner===0&&b.type==='hut'&&b.progress===1&&!b.blessed),point);if(!hut||dist(hut,point)>1)return toast('Click a completed, unblessed friendly hut.');hut.blessed=true;hut.belief=35;faith[0]-=cost;renderObjects();ping(hut.x,hut.z,gem[0]);log('Hut blessed. Its faith income now grows permanently.');guideAdvance(4)}
 else if(mode==='raise'||mode==='lower'){let result=terrainBrush(x,z,mode==='raise'?1:-1,true);if(!result.changed)return toast('No eligible tiles in this area. Red terrace markers need shaping.');faith[0]-=cost;renderTerrain();renderObjects();log(result.terrace?'One terrace tile aligned. Sacred stone faith income rises.':`One tile ${mode==='raise'?'raised':'lowered'}.`)}
 else if(mode==='bridge'){let changed=0;for(let dx=-2;dx<=2;dx++){let tile=at(x+dx,z);if(tile&&tile.h===0){tile.h=1;changed++}}if(!changed)return toast('Cast across water to create a crossing.');faith[0]-=cost;renderTerrain();renderObjects();log('Land bridge opens a path for your followers.')}
 updateUI()
}
function guideAdvance(n){if(guideStep!==n)return;guideStep++;updateGuide()}
const guideText=[['1 · Welcome a follower','Choose Convert and click a nearby grey wildman. More followers earn faith faster.'],['2 · Build a village','Choose Place Hut and click clear land near your village. Watch braves gather wood and build.'],['3 · Claim a sacred stone','Move the shaman beside a stone and hold for three seconds, or use a Ritual. Stones generate faith.'],['4 · Choose worshippers','Choose Worship and click your stone. Two workers will leave construction and begin generating faith.'],['5 · Bless a hut','Bless a completed hut to create another worship site. Choose when to recall followers to build again.'],['The faith is yours','Claim stones, grow your people, and choose when to invest your faith. First to 500 devotion wins.']];
function updateGuide(){let g=$('#guide');if(g.hidden)return;$('#guideTitle').textContent=guideText[guideStep][0];$('#guideBody').textContent=guideText[guideStep][1]}
function updateUI(){let playerRate=income(0),enemyRate=income(1);$('#population').textContent=people.filter(p=>p.owner===0).length;$('#enemy').textContent=people.filter(p=>p.owner===1).length;$('#faith').textContent=Math.floor(faith[0])+'/160';$('#devotion').textContent=Math.floor(devotion[0])+'/'+DEVOTION_GOAL;$('#tribe').innerHTML=`${buildings.filter(b=>b.owner===0&&b.progress===1).length} buildings · ${buildings.filter(b=>b.owner===0&&b.blessed).length} blessed<br>${people.filter(p=>p.owner===0&&p.type==='brave'&&p.role==='worker').length} workers · ${people.filter(p=>p.owner===0&&p.role==='worshipper').length} worshippers · ${shrines.filter(s=>s.owner===0).length}/3 stones<br>Local belief: ${[...shrines,...buildings].filter(s=>validWorshipSite(s,0)).map(s=>`${shrines.includes(s)?`Stone ${terraceScore(s)}/8`:'Hut'} ${Math.round(siteBelief(s))}%${siteNeeds(s,0).healthy?' ↑':' ↓'}`).join(' · ')||'Claim a stone or bless a hut'}`;$('#status').textContent=`${running?'World running':'Paused'} · ${speed}× · ${Math.floor(elapsed)}s · 42×30 island · Faith +${playerRate.toFixed(1)}/s`;$('#objective').innerHTML=`<b>DEVOTION ${Math.floor(devotion[0])} / ${DEVOTION_GOAL} · EMBER ${Math.floor(devotion[1])} / ${DEVOTION_GOAL}</b><span>Faith income +${playerRate.toFixed(1)}/s · Ember +${enemyRate.toFixed(1)}/s · Stones ${shrines.filter(s=>s.owner===0).length} : ${shrines.filter(s=>s.owner===1).length}</span><div class="devotion-race"><div class="track"><i style="width:${Math.min(100,devotion[0]/DEVOTION_GOAL*100)}%"></i></div><div class="track ember"><i style="width:${Math.min(100,devotion[1]/DEVOTION_GOAL*100)}%"></i></div></div>`;$('#hint').textContent=hints[mode];updateDecision();updateSitePanel();document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))})}
function cameraTarget(x,z){target.set(x-W/2,0,z-H/2);updateCamera()}
function updateCamera(){let size=15/zoom,aspect=Math.max(.5,stage.clientWidth/stage.clientHeight);camera.left=-size*aspect;camera.right=size*aspect;camera.top=size;camera.bottom=-size;camera.position.set(target.x+Math.sin(angle)*size*1.4,size*1.1,target.z+Math.cos(angle)*size*1.4);camera.lookAt(target);camera.updateProjectionMatrix()}
function pick(e){let r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);let hits=ray.intersectObjects(terrain.children);if(!hits.length)return null;let v=hits[0].point;return{x:clamp(Math.round(v.x+W/2-.5),0,W-1),z:clamp(Math.round(v.z+H/2-.5),0,H-1)}}
stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,moved:false,button:e.button}});stage.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.moved=true;if(drag.moved){if(drag.button===2)angle+=dx*.007;else{let a=angle,scale=15/zoom/Math.max(stage.clientHeight,1)*2;target.x+=(-dx*Math.cos(a)+dy*Math.sin(a))*scale;target.z+=(dx*Math.sin(a)+dy*Math.cos(a))*scale}updateCamera()}drag.x=e.clientX;drag.y=e.clientY});stage.addEventListener('pointerup',e=>{if(!drag)return;let moved=drag.moved;drag=null;if(!moved){let p=pick(e);if(p)action(p.x,p.z)}});stage.addEventListener('contextmenu',e=>e.preventDefault());stage.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY<0?1.12:.89),.55,2.2);updateCamera()},{passive:false});
$('#sitePanel').onclick=e=>{let button=e.target.closest('[data-site-action]');if(!button||button.disabled||!selectedSite)return;let site=selectedSite;if(button.dataset.siteAction==='close'){selectedSite=null;updateSitePanel();return}if(button.dataset.siteAction==='festival'){festival(site);return}if(button.dataset.siteAction==='assign'){let n=assignWorshippers(0,site,2);if(n){log(`${n} followers head to worship. Faith rises when they arrive.`);guideAdvance(3)}else toast('Keep three free workers in your tribe to build and gather.')}if(button.dataset.siteAction==='recall'){let n=0;for(let p of people.filter(p=>p.owner===0&&p.worshipSite===site)){p.role='worker';p.worshipSite=null;p.goal=null;p.job='RETURNING TO WORK';n++}if(n)log(`${n} followers return to work.`)}updateUI()};
$('#home').onclick=()=>cameraTarget(shaman.x,shaman.z);$('#rotateL').onclick=()=>{angle-=Math.PI/6;updateCamera()};$('#rotateR').onclick=()=>{angle+=Math.PI/6;updateCamera()};$('#zoomIn').onclick=()=>{zoom=clamp(zoom*1.2,.55,2.2);updateCamera()};$('#zoomOut').onclick=()=>{zoom=clamp(zoom/1.2,.55,2.2);updateCamera()};$('#pause').onclick=()=>{running=!running;$('#pause').textContent=running?'PAUSE':'RESUME';updateUI()};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('#speed').textContent=speed+'× SPEED';updateUI()};$('#restart').onclick=makeWorld;$('#guideSkip').onclick=()=>$('#guide').hidden=true;$('#help').onclick=()=>$('#instructions').showModal();$('#closeHelp').onclick=()=>$('#instructions').close();
new ResizeObserver(()=>{let w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);updateCamera()}).observe(stage);setupButtons();makeWorld();let last=performance.now(),acc=0;function frame(now){requestAnimationFrame(frame);for(let f of [...fx]){let age=(now-f.born)/1600;if(age>=1){fxGroup.remove(f.marker);fx.splice(fx.indexOf(f),1)}else f.marker.scale.setScalar(.3+age*.85)}let dt=Math.min((now-last)/1000,.1);last=now;if(running&&!ended){acc+=dt*speed;while(acc>=1/30){ai(1/30);acc-=1/30}}renderUnits(now);gem[0].emissiveIntensity=1.5+Math.sin(now*.003)*.5;gem[1].emissiveIntensity=1.5+Math.sin(now*.003+2)*.5;renderer.render(scene,camera)}requestAnimationFrame(frame);
