import * as THREE from '../vendor/three.module.js';
const $=s=>document.querySelector(s), W=30,H=22, clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const colors=[0x78c5ac,0xe48369,0xb9b7a5];
const stage=$('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color(0x567e8b);scene.fog=new THREE.Fog(0x567e8b,28,58);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;stage.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-13,13,9,-9,.1,100),target=new THREE.Vector3(0,0,0);let angle=Math.PI/4,zoom=1,drag=null;
scene.add(new THREE.HemisphereLight(0xd5eeff,0x4c5143,2.6));const sun=new THREE.DirectionalLight(0xffe5b0,2.9);sun.position.set(-13,23,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=22;sun.shadow.camera.bottom=-22;sun.shadow.bias=-.0005;scene.add(sun);
const water=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x376d78,roughness:.42,metalness:.14}));water.rotation.x=-Math.PI/2;water.position.y=.03;scene.add(water);
const terrain=new THREE.Group(),objects=new THREE.Group(),unitsGroup=new THREE.Group(),fxGroup=new THREE.Group();scene.add(terrain,objects,unitsGroup,fxGroup);
const box=new THREE.BoxGeometry(1,1,1),sphere=new THREE.SphereGeometry(1,10,8),cone=new THREE.ConeGeometry(1,1,8),cyl=new THREE.CylinderGeometry(1,1,1,8),ringGeo=new THREE.TorusGeometry(1,.035,5,28);
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.92,...extra});const landMats=[null,mat(0x988665),mat(0x869a66),mat(0x73a26a),mat(0x7e9569),mat(0x999a81)],sideMats=[null,mat(0x605747),mat(0x5e6650),mat(0x52684b),mat(0x53624d),mat(0x666b5c)];const woodMat=mat(0x725746),roofMats=[mat(0x446a56),mat(0xa45043)],stoneMat=mat(0xc0ad83),wildMat=mat(0xc8c0a4),trunkMat=mat(0x654c38),leafMats=[mat(0x294e3c),mat(0x38664a),mat(0x54825a)],waterMat=mat(0x9cc4bc,{transparent:true,opacity:.35});
let seed=2026,tiles=[],buildings=[],people=[],mana=70,respawn=0,mode='convert',running=true,speed=1,elapsed=0,tick=0,aiClock=0,ended='',logs=[],guideStep=0,toastTimer=0,fx=[],shaman;
const rand=(x,y,s=seed)=>{let n=Math.imul(x+11,374761393)+Math.imul(y+23,668265263)+Math.imul(s,2246822519);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967296};
const at=(x,z)=>x>=0&&z>=0&&x<W&&z<H?tiles[z*W+x]:null;const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);const height=(x,z)=>at(Math.round(x),Math.round(z))?.h||0;const pos=(x,z)=>new THREE.Vector3(x-W/2+.5,height(x,z)*.48,z-H/2+.5);
function mesh(geo,material,parent,x,y,z,sx=1,sy=1,sz=1){let o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function clear(group){while(group.children.length){let child=group.children[0];group.remove(child);if(child.geometry&&!([box,sphere,cone,cyl].includes(child.geometry)))child.geometry.dispose()}}
function log(s){logs.unshift(s);logs=logs.slice(0,5);$('#events').innerHTML=logs.map(v=>`<p>${v}</p>`).join('');toast(s)}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2600)}
function makeWorld(){clear(unitsGroup);seed=Math.floor(Math.random()*900000)+1000;tiles=[];buildings=[];people=[];mana=70;respawn=0;elapsed=0;tick=0;aiClock=0;ended='';running=true;speed=1;guideStep=0;logs=[];mode='convert';$('#result').hidden=true;$('#pause').textContent='PAUSE';$('#speed').textContent='1× SPEED';for(let z=0;z<H;z++)for(let x=0;x<W;x++){let island=Math.min(x,W-1-x,z,H-1-z),noise=rand(Math.floor(x/3),Math.floor(z/3))*.7+rand(x,z)*.3;let h=island<2||noise<.18?0:clamp(Math.floor(noise*4.5),1,4);tiles.push({h,tree:h>0&&rand(x,z,seed+1)>.76,wood:0,building:null})}for(let camp of [{x:6,z:10},{x:23,z:10}])for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){let t=at(camp.x+dx,camp.z+dz);if(t){t.h=2;if(Math.abs(dx)<2&&Math.abs(dz)<2)t.tree=false}}for(let z=7;z<=13;z++)for(let x=11;x<=18;x++){let t=at(x,z);if(t)t.h=2}addBuilding(6,10,0,'hearth',true);addBuilding(23,10,1,'hearth',true);addBuilding(4,9,0,'hut',true);addBuilding(25,11,1,'hut',true);for(let [x,z,owner] of [[8,10,0],[21,10,1]]){at(x,z).tree=false;addBuilding(x,z,owner,'hut')}for(let i=0;i<5;i++){addPerson(0,5+rand(i,0),9+rand(i,1),'brave');addPerson(1,24+rand(i,2),10+rand(i,3),'brave')}for(let i=0;i<7;i++)addPerson(2,10+rand(i,5)*7,7+rand(i,6)*7,'wild');shaman=addPerson(0,6,11,'shaman');addPerson(1,23,9,'shaman');renderTerrain();renderObjects();updateUI();updateGuide();log('Convert wildmen, build huts, and challenge the Ember tribe.');cameraTarget(14,10)}
function addBuilding(x,z,owner,type,complete=false){let t=at(x,z);if(!t||t.h<1||t.building)return null;let b={x,z,owner,type,progress:complete?1:0,wood:complete?3:0,hp:type==='hearth'?210:100,pop:0,spawn:0};buildings.push(b);t.building=b;return b}
function addPerson(owner,x,z,type){let p={owner,x,z,type,hp:type==='shaman'?110:45,goal:null,work:0,carry:0,idle:0,raid:false,job:type==='wild'?'ROAMING':'IDLE'};people.push(p);return p}
function renderTerrain(){clear(terrain);for(let z=0;z<H;z++)for(let x=0;x<W;x++){let t=at(x,z);if(!t.h)continue;let p=pos(x,z),y=t.h*.48,material=landMats[t.h];mesh(box,sideMats[t.h],terrain,p.x,y/2-.015,p.z,.98,y,.98);mesh(box,material,terrain,p.x,y-.035,p.z,.99,.09,.99);if(rand(x,z,seed+71)>.48){let pebble=mesh(sphere,rand(x,z,seed+74)>.5?stoneMat:landMats[Math.min(5,t.h+1)],terrain,p.x+(rand(x,z,seed+75)-.5)*.6,y+.012,p.z+(rand(x,z,seed+76)-.5)*.6,.05,.03,.08);pebble.castShadow=false}}}
function renderObjects(){clear(objects);for(let z=0;z<H;z++)for(let x=0;x<W;x++){let t=at(x,z);if(!t.tree||!t.h)continue;let p=pos(x,z),v=rand(x,z,seed+2);mesh(cyl,trunkMat,objects,p.x,p.y+.24,p.z,.09,.5,.09);mesh(cone,leafMats[Math.floor(v*3)],objects,p.x,p.y+.66,p.z,.37,.8,.37);mesh(cone,leafMats[Math.floor(v*3)],objects,p.x,p.y+.93,p.z,.26,.62,.26)}for(let b of buildings){let p=pos(b.x,b.z),roof=roofMats[b.owner];if(b.progress<1){let marker=mesh(box,roof,objects,p.x,p.y+.025,p.z,.76,.05,.76);marker.material=roof;for(let dx of [-.31,.31])for(let dz of [-.31,.31])mesh(cyl,woodMat,objects,p.x+dx,p.y+.17,p.z+dz,.045,.32,.045);if(b.wood)mesh(box,woodMat,objects,p.x,p.y+.1,p.z,.4,.13,.4);continue}if(b.type==='hearth'){mesh(cyl,stoneMat,objects,p.x,p.y+.16,p.z,.78,.32,.78);mesh(cyl,roof,objects,p.x,p.y+.48,p.z,.45,.45,.45);mesh(cone,roof,objects,p.x,p.y+.92,p.z,.6,.55,.6);mesh(sphere,mat(b.owner===0?0xafffeb:0xffa28b,{emissive:b.owner===0?0x2f9d81:0x9d2d23,emissiveIntensity:1.5}),objects,p.x,p.y+1.2,p.z,.14,.14,.14)}else{let scale=b.hp<45?.8:1;mesh(box,woodMat,objects,p.x,p.y+.3,p.z,.78*scale,.58*scale,.7*scale);let r=mesh(cone,roof,objects,p.x,p.y+.7*scale,p.z,.64*scale,.4*scale,.64*scale);r.rotation.y=Math.PI/4;mesh(box,stoneMat,objects,p.x,p.y+.13,p.z+.37*scale,.16*scale,.24*scale,.02)}}}
// Each follower owns a small character rig. Geometry and materials are shared across rigs.
const skin=[mat(0xc89f79),mat(0xa97756),mat(0xb3a080)],cloth=[mat(0x397b76),mat(0xa04f43),mat(0x776c59)],trim=[mat(0x95d5ba),mat(0xebaa7c),mat(0xd7c29b)],hair=[mat(0x392d2b),mat(0x4b3026),mat(0x555047)],eyes=mat(0x252523),staffMat=mat(0x665038),gem=[mat(0x8fffe1,{emissive:0x39bbaa,emissiveIntensity:2}),mat(0xffac83,{emissive:0xd94c32,emissiveIntensity:2})],shadowMat=mat(0x12252a,{transparent:true,opacity:.3,depthWrite:false}),healthBack=mat(0x382e2a),healthFill=mat(0xb9dd99);
function followerRig(p){let owner=p.owner,kind=p.type,sh=kind==='shaman',wild=owner===2,group=new THREE.Group(),body=new THREE.Group();group.add(body);group.userData={body,legs:[],arms:[],kind:owner+':'+kind};unitsGroup.add(group);
 let base=owner===2?2:owner,scale=sh?1.28:1;body.scale.setScalar(scale);
 let shadow=mesh(sphere,shadowMat,group,0,.035,0,.27,.015,.22);shadow.castShadow=false;
 if(sh){let halo=mesh(ringGeo,gem[owner],group,0,.065,0,.42,.42,.42);halo.rotation.x=Math.PI/2;halo.castShadow=false;group.userData.halo=halo}
 for(let side of [-1,1]){let leg=new THREE.Group();leg.position.set(side*.105,.35,0);body.add(leg);mesh(cyl,wild?skin[2]:cloth[base],leg,0,-.15,0,.068,.31,.068);mesh(box,wild?skin[2]:staffMat,leg,0,-.3,.06,.1,.08,.19);group.userData.legs.push(leg)}
 if(sh){mesh(cone,cloth[base],body,0,.44,0,.31,.66,.28);mesh(cone,trim[base],body,0,.31,0,.28,.15,.27);mesh(sphere,cloth[base],body,0,.75,-.06,.26,.19,.21);mesh(sphere,trim[base],body,0,.82,.1,.18,.065,.12)}
 else{mesh(box,wild?skin[2]:cloth[base],body,0,.59,0,.38,.42,.23);mesh(box,wild?cloth[2]:trim[base],body,0,.39,.01,.39,.09,.26);if(!wild){mesh(box,staffMat,body,0,.67,-.15,.3,.28,.1);mesh(box,trim[base],body,0,.66,-.21,.31,.08,.055)}}
 for(let side of [-1,1]){let arm=new THREE.Group();arm.position.set(side*.245,sh?.79:.73,0);body.add(arm);mesh(cyl,sh?cloth[base]:skin[base],arm,side*.04,-.13,0,.07,.28,.07);mesh(sphere,skin[base],arm,side*.04,-.29,.01,.065,.065,.065);group.userData.arms.push(arm)}
 mesh(sphere,skin[base],body,0,sh?1.05:.96,.02,.17,.19,.15);mesh(sphere,hair[base],body,0,sh?1.18:1.075,-.045,.175,.09,.15);
 for(let side of [-1,1])mesh(sphere,eyes,body,side*.072,sh?1.065:.975,.16,.018,.021,.011);
 if(sh){let hood=mesh(cone,cloth[base],body,0,1.23,-.065,.225,.35,.23);hood.rotation.x=-.15;mesh(cyl,staffMat,body,.35,.7,.08,.028,1.1,.028);mesh(sphere,gem[owner],body,.35,1.28,.08,.115,.12,.115);mesh(ringGeo,gem[owner],body,.35,1.28,.08,.18,.18,.18);}
 else if(wild){mesh(cone,hair[2],body,0,1.11,-.04,.2,.23,.2);mesh(sphere,hair[2],body,0,.87,-.025,.16,.06,.16)}
 else{let cap=mesh(cone,cloth[base],body,0,1.12,-.02,.19,.15,.18);cap.rotation.z=-.17;mesh(box,trim[base],body,0,1.055,.02,.35,.045,.32);}
 if(!sh&&!wild){let bundle=mesh(cyl,woodMat,body,0,.55,.25,.065,.38,.065);bundle.rotation.z=Math.PI/2;bundle.visible=false;group.userData.bundle=bundle}let hp=new THREE.Group();hp.position.set(0,sh?1.62:1.38,0);group.add(hp);mesh(box,healthBack,hp,0,0,0,.45,.055,.025);let fill=mesh(box,healthFill,hp,-.22,0,.018,.43,.036,.025);group.userData.health=hp;group.userData.fill=fill;return group}
function renderUnits(time){for(let child of [...unitsGroup.children])if(!people.some(p=>p.visual===child))unitsGroup.remove(child);
 for(let p of people){let kind=p.owner+':'+p.type;if(!p.visual||p.visual.userData.kind!==kind){if(p.visual)unitsGroup.remove(p.visual);p.visual=followerRig(p);p.lastX=p.x;p.lastZ=p.z;p.walkPhase=0}
 let rig=p.visual,v=pos(p.x,p.z),dx=p.x-p.lastX,dz=p.z-p.lastZ,moving=Math.hypot(dx,dz)>.0005;rig.position.set(v.x,v.y,v.z);if(moving){rig.rotation.y=Math.atan2(dx,dz);p.walkPhase+=Math.hypot(dx,dz)*18}p.lastX=p.x;p.lastZ=p.z;
 let swing=moving?Math.sin(p.walkPhase)*.5:Math.sin(time*.0015+p.x)*.035;rig.userData.legs[0].rotation.x=swing;rig.userData.legs[1].rotation.x=-swing;rig.userData.arms[0].rotation.x=-swing*.7;rig.userData.arms[1].rotation.x=swing*.7;rig.userData.body.position.y=(moving?Math.abs(Math.sin(p.walkPhase))*.025:Math.sin(time*.002+p.x)*.018);if(rig.userData.halo)rig.userData.halo.rotation.z=time*.00045;
 if(rig.userData.bundle)rig.userData.bundle.visible=!!p.carry;let max=p.type==='shaman'?110:45,hp=clamp(p.hp/max,0,1);rig.userData.health.visible=hp<.99;rig.userData.fill.scale.x=hp;rig.userData.fill.position.x=-.225+.215*hp;}}

function validLand(x,z){let t=at(x,z);return !!t&&t.h>0}
function nearest(list,p){let best=null,d=Infinity;for(let item of list){let n=dist(item,p);if(n<d){best=item;d=n}}return best}
function move(p,goal,dt,rate=1){if(!goal)return;let dx=goal.x-p.x,dz=goal.z-p.z,d=Math.hypot(dx,dz);if(d<.14){p.goal=null;return}let step=Math.min(d,dt*rate);let x=p.x+dx/d*step,z=p.z+dz/d*step;if(validLand(Math.round(x),Math.round(z))){p.x=x;p.z=z}else p.goal=null}
function ai(dt){
 elapsed+=dt;
 if(respawn>0){respawn-=dt;if(respawn<=0&&people.some(p=>p.owner===0)&&buildings.some(b=>b.owner===0&&b.type==='hearth')){shaman=addPerson(0,6,10,'shaman');log('Your shaman has returned to the hearth.')}}
 mana=clamp(mana+dt*(.25+people.filter(p=>p.owner===0).length*.055),0,200);aiClock+=dt;
 for(let p of [...people]){
  if(!people.includes(p))continue;
  if(p.type==='wild'){p.job='ROAMING';p.idle-=dt;if(p.idle<=0&&!p.goal){let x=clamp(Math.round(p.x+(rand(Math.floor(elapsed),people.indexOf(p))-.5)*4),1,W-2),z=clamp(Math.round(p.z+(rand(people.indexOf(p),Math.floor(elapsed))-.5)*4),1,H-2);if(validLand(x,z))p.goal={x,z};p.idle=3+rand(x,z)*3}if(p.goal)move(p,p.goal,dt,.45);continue}
  let own=p.owner,enemy=1-own;if(p.goal){move(p,p.goal,dt,p.type==='shaman'?1.5:1.3);continue}
  let foe=nearest(people.filter(q=>q.owner===enemy),p);
  if(foe&&dist(foe,p)<(p.type==='shaman'?2.5:1.05)){p.work+=dt;if(p.work>.72){p.work=0;foe.hp-=p.type==='shaman'?13:8;if(foe.hp<=0){people.splice(people.indexOf(foe),1);if(foe===shaman){respawn=14;log('Your shaman has fallen. She returns at the hearth in 14 seconds if braves survive.')}}}continue}
  if(p.type==='shaman'){if(own===1){let wild=nearest(people.filter(q=>q.owner===2),p);if(wild&&dist(wild,p)<4&&aiClock>4){wild.owner=1;wild.type='brave';wild.hp=45;wild.goal=null;aiClock=0;log('Ember converted a wildman.')}else if(wild&&dist(wild,p)>4)p.goal={x:wild.x,z:wild.z}}continue}
  if(p.raid){p.job='RAIDING';let target=nearest(buildings.filter(b=>b.owner===enemy&&b.progress===1),p);if(!target){p.raid=false;continue}if(dist(p,target)>1)p.goal={x:target.x+(p.x>target.x?.7:-.7),z:target.z};else{p.work+=dt;if(p.work>=1.1){p.work=0;target.hp-=8;if(target.hp<=0){at(target.x,target.z).building=null;buildings.splice(buildings.indexOf(target),1);renderObjects();log(`${own?'Ember destroyed your':'Your braves destroyed an Ember'} building.`)}}}continue}
  let site=nearest(buildings.filter(b=>b.owner===own&&b.progress<1),p);
  if(site){if(p.carry){p.job='HAULING WOOD';if(dist(p,site)>1){p.goal={x:site.x+(p.x>site.x?.7:-.7),z:site.z};continue}site.wood=Math.min(3,site.wood+1);p.carry=0;renderObjects();if(site.wood===3&&own===0)log('Wood delivered. Braves are building the hut.');continue}
   if(site.wood<3){p.job='GATHERING WOOD';let trees=[];for(let z=Math.max(1,site.z-6);z<=Math.min(H-2,site.z+6);z++)for(let x=Math.max(1,site.x-6);x<=Math.min(W-2,site.x+6);x++)if(at(x,z)?.tree&&dist({x,z},site)<=6)trees.push({x,z});let tree=nearest(trees,p);if(tree){if(dist(p,tree)>.6)p.goal=tree;else{p.work+=dt;if(p.work>.75){p.work=0;at(tree.x,tree.z).tree=false;p.carry=1;renderObjects()}}continue}}
   if(site.wood>=3){p.job='BUILDING HUT';if(dist(p,site)>1){p.goal={x:site.x+(p.x>site.x?.7:-.7),z:site.z};continue}site.progress=clamp(site.progress+dt*.16,0,1);if(site.progress===1){log(`${own?'Ember':'Your'} hut completed.`);renderObjects()}continue}}
  // An idle brave visits occupied huts and patrols around its camp.
  p.job='PATROLLING';p.idle-=dt;if(p.idle<=0){let homes=buildings.filter(b=>b.owner===own&&b.progress===1),home=homes[Math.floor(rand(people.indexOf(p),Math.floor(elapsed))*homes.length)];if(home){let x=clamp(home.x+Math.round((rand(Math.floor(elapsed),people.indexOf(p)+7)-.5)*5),1,W-2),z=clamp(home.z+Math.round((rand(people.indexOf(p)+9,Math.floor(elapsed))-.5)*5),1,H-2);if(validLand(x,z))p.goal={x,z}}p.idle=2+rand(Math.floor(elapsed),people.indexOf(p))*3}
 }
 for(let b of buildings){if(b.progress<1)continue;let nearby=people.filter(p=>p.owner===b.owner&&p.type==='brave'&&dist(p,b)<3).length;b.pop=nearby;b.spawn+=dt*(b.type==='hut'?.12:.025)*(1+Math.min(nearby,3)*.23);if(b.spawn>=1&&people.filter(p=>p.owner===b.owner).length<40){b.spawn=0;addPerson(b.owner,b.x+.35,b.z+.35,'brave');if(b.owner===0)log('A new brave emerges from a hut.')}}
 if(aiClock>16){aiClock=0;let camp=buildings.find(b=>b.owner===1&&b.type==='hearth');if(camp){let raiders=people.filter(p=>p.owner===1&&p.type==='brave'&&!p.raid).slice(0,2);let target=nearest(buildings.filter(b=>b.owner===0),camp);if(target&&raiders.length){for(let p of raiders){p.raid=true;p.goal={x:target.x,z:target.z}}log('Ember braves are raiding your settlement.')}let x=camp.x-2-Math.floor(rand(Math.floor(elapsed),1)*3),z=camp.z+(rand(Math.floor(elapsed),2)>.5?2:-2);if(validLand(x,z)&&!at(x,z).building){at(x,z).tree=false;addBuilding(x,z,1,'hut');renderObjects();log('Ember marked a new hut site.')}}}
 if(people.filter(p=>p.owner===1).length===0)finish(true);if(people.filter(p=>p.owner===0).length===0)finish(false);updateUI()
}

function finish(win){if(ended)return;ended=win?'victory':'defeat';running=false;$('#result').hidden=false;$('#result').innerHTML=`<h2>${win?'YOUR TRIBE PREVAILS':'THE EMBER PREVAILS'}</h2><p>${win?'Your followers have defeated the rival tribe.':'Your tribe has fallen.'}</p><button id="again">PLAY AGAIN</button>`;$('#again').onclick=makeWorld}
const commands=[['move','MOVE SHAMAN','Free'],['hut','PLACE HUT','Braves build'],['attack','ATTACK','Send braves'],['inspect','INSPECT','Free']];const spells=[['convert','CONVERT','20 mana'],['raise','RAISE LAND','8 mana'],['lower','LOWER LAND','8 mana'],['bridge','LAND BRIDGE','30 mana'],['blast','BLAST','35 mana']];
function setupButtons(){for(let [el,items] of [['#commands',commands],['#spells',spells]])$(el).innerHTML=items.map(([id,label,cost])=>`<button data-mode="${id}">${label}<small>${cost}</small></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;updateUI()})}
const spellCosts={convert:20,raise:8,lower:8,bridge:30,blast:35};const hints={move:'Click a destination to move your shaman into spell range.',hut:'Click open land near your camp. Braves gather wood and build the hut.',attack:'Click a destination to send available braves.',inspect:'Click a follower, building or tile for details.',convert:'Click a grey wildman within 5 tiles of your shaman.',raise:'Raise a 3×3 area; use terrain to make new buildable land.',lower:'Lower a 3×3 area; water blocks movement.',bridge:'Connect two patches of land across a channel.',blast:'Damage enemy followers and buildings within the blast.'};
function action(x,z){let t=at(x,z);if(!t||ended)return;let point={x,z},range=dist(shaman,point);if(mode==='inspect'){let person=nearest(people,point),building=nearest(buildings,point);if(person&&dist(person,point)<.7)toast(`${person.owner===2?'Wildman':person.owner?'Ember':'Verdant'} ${person.type} · ${person.job||'IDLE'} · ${Math.ceil(person.hp)} health`);else if(building&&dist(building,point)<.9)toast(`${building.owner?'Ember':'Verdant'} ${building.type} · ${Math.ceil(building.hp)} health · ${Math.round(building.progress*100)}% built`);else toast(`Terrain height ${t.h} · ${t.tree?'trees':'clear'} · ${x}, ${z}`);return}
if(mode==='move'){if(!people.includes(shaman))return toast('The shaman is awaiting rebirth.');if(!t.h)return toast('The shaman cannot walk into water.');shaman.goal=point;guideAdvance(3);return}
if(mode==='hut'){if(!t.h||t.building||t.tree)return toast('Place huts on clear land.');if(dist(point,{x:6,z:10})>10&&!buildings.some(b=>b.owner===0&&dist(point,b)<5))return toast('Build within reach of your tribe.');addBuilding(x,z,0,'hut');renderObjects();log('Hut plan placed. Braves need nearby trees to build it.');guideAdvance(1);return}
if(mode==='attack'){let soldiers=people.filter(p=>p.owner===0&&p.type==='brave');if(!soldiers.length)return toast('You need braves to attack.');soldiers.forEach((p,i)=>{p.goal={x:x+(i%3-1)*.3,z:z+Math.floor(i/3)*.2};p.raid=true});log(`${soldiers.length} braves march toward the target.`);guideAdvance(2);return}
let cost=spellCosts[mode];if(!people.includes(shaman))return toast('Wait for your shaman to return.');if(mana<cost)return toast(`Need ${cost} mana; your followers replenish it over time.`);if(range>5.5)return toast('Out of range. Move the shaman closer first.');if(mode==='convert'){let wild=nearest(people.filter(p=>p.owner===2),point);if(!wild||dist(wild,point)>.8)return toast('Target a grey wildman.');wild.owner=0;wild.type='brave';wild.hp=45;mana-=cost;log('Wildman converted into a brave.');guideAdvance(0)}else if(mode==='raise'||mode==='lower'){let changed=0;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){let tile=at(x+dx,z+dz);if(!tile||tile.building)continue;let next=clamp(tile.h+(mode==='raise'?1:-1),0,5);if(next!==tile.h){tile.h=next;if(next===0)tile.tree=false;changed++}}if(!changed)return toast('Buildings block this terrain.');mana-=cost;renderTerrain();renderObjects();log(`${changed} terrain tiles ${mode==='raise'?'raised':'lowered'}.`)}else if(mode==='bridge'){let changed=0;for(let dx=-2;dx<=2;dx++){let tile=at(x+dx,z);if(tile&&tile.h===0){tile.h=1;changed++}}if(!changed)return toast('Cast across a water gap.');mana-=cost;renderTerrain();renderObjects();log('Land bridge opens a crossing.')}else if(mode==='blast'){let victims=people.filter(p=>p.owner===1&&dist(p,point)<1.8);let structures=buildings.filter(b=>b.owner===1&&dist(b,point)<1.8);if(!victims.length&&!structures.length)return toast('Aim at enemy followers or buildings.');mana-=cost;for(let p of victims){p.hp-=55;if(p.hp<=0)people.splice(people.indexOf(p),1)}for(let b of structures){b.hp-=55;if(b.hp<=0){at(b.x,b.z).building=null;buildings.splice(buildings.indexOf(b),1)}}renderObjects();log(`Blast struck ${victims.length} follower${victims.length===1?'':'s'} and ${structures.length} building${structures.length===1?'':'s'}.`)}updateUI()}
function guideAdvance(n){if(guideStep!==n)return;guideStep++;updateGuide()}
const guideText=[['1 · Convert the wild','Choose Convert, then click a grey wildman near your shaman. Your new brave can build.'],['2 · Grow a village','Choose Place Hut, then click clear land near your camp. Braves will find trees and construct it.'],['3 · Take the initiative','Choose Attack and click near the red camp. Watch your braves march and fight.'],['4 · Command the shaman','Choose Move Shaman and click near the front. Cast Blast when she is in range.'],['The world is yours','Expand your tribe, shape paths, and defeat the Ember. Pause whenever you need time to think.']];
function updateGuide(){let g=$('#guide');if(g.hidden)return;$('#guideTitle').textContent=guideText[guideStep][0];$('#guideBody').textContent=guideText[guideStep][1]}
function updateUI(){$('#population').textContent=people.filter(p=>p.owner===0).length;$('#enemy').textContent=people.filter(p=>p.owner===1).length;$('#mana').textContent=Math.floor(mana)+'/200';$('#shaman').textContent=people.includes(shaman)?'READY':Math.ceil(respawn)+'s';$('#tribe').innerHTML=`${buildings.filter(b=>b.owner===0&&b.progress===1).length} buildings · ${buildings.filter(b=>b.owner===0&&b.progress<1).length} plans<br>${people.filter(p=>p.owner===0&&p.type==='brave').length} braves · ${people.filter(p=>p.owner===2).length} wildmen`;$('#status').textContent=`${running?'World running':'Paused'} · ${speed}× · ${Math.floor(elapsed)}s elapsed`;$('#hint').textContent=hints[mode];document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))})}
function cameraTarget(x,z){target.set(x-W/2,0,z-H/2);updateCamera()}
function updateCamera(){let size=15/zoom,aspect=Math.max(.5,stage.clientWidth/stage.clientHeight);camera.left=-size*aspect;camera.right=size*aspect;camera.top=size;camera.bottom=-size;camera.position.set(target.x+Math.sin(angle)*size*1.4,size*1.1,target.z+Math.cos(angle)*size*1.4);camera.lookAt(target);camera.updateProjectionMatrix()}
function pick(e){let r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);let hits=ray.intersectObjects(terrain.children);if(!hits.length)return null;let v=hits[0].point;return{x:clamp(Math.round(v.x+W/2-.5),0,W-1),z:clamp(Math.round(v.z+H/2-.5),0,H-1)}}
stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,moved:false,button:e.button}});stage.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.moved=true;if(drag.moved){if(drag.button===2)angle+=dx*.007;else{let a=angle,scale=15/zoom/Math.max(stage.clientHeight,1)*2;target.x+=(-dx*Math.cos(a)+dy*Math.sin(a))*scale;target.z+=(dx*Math.sin(a)+dy*Math.cos(a))*scale}updateCamera()}drag.x=e.clientX;drag.y=e.clientY});stage.addEventListener('pointerup',e=>{if(!drag)return;let moved=drag.moved;drag=null;if(!moved){let p=pick(e);if(p)action(p.x,p.z)}});stage.addEventListener('contextmenu',e=>e.preventDefault());stage.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY<0?1.12:.89),.55,2.2);updateCamera()},{passive:false});
$('#rotateL').onclick=()=>{angle-=Math.PI/6;updateCamera()};$('#rotateR').onclick=()=>{angle+=Math.PI/6;updateCamera()};$('#zoomIn').onclick=()=>{zoom=clamp(zoom*1.2,.55,2.2);updateCamera()};$('#zoomOut').onclick=()=>{zoom=clamp(zoom/1.2,.55,2.2);updateCamera()};$('#pause').onclick=()=>{running=!running;$('#pause').textContent=running?'PAUSE':'RESUME';updateUI()};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('#speed').textContent=speed+'× SPEED';updateUI()};$('#restart').onclick=makeWorld;$('#guideSkip').onclick=()=>$('#guide').hidden=true;$('#help').onclick=()=>$('#instructions').showModal();$('#closeHelp').onclick=()=>$('#instructions').close();
new ResizeObserver(()=>{let w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);updateCamera()}).observe(stage);setupButtons();makeWorld();let last=performance.now(),acc=0;function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.1);last=now;if(running&&!ended){acc+=dt*speed;while(acc>=1/30){ai(1/30);acc-=1/30}}renderUnits(now);renderer.render(scene,camera)}requestAnimationFrame(frame);
